### ISSUE TITLE
Interview-Overlay: Fotocredits

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#103]
Bei Loraine, Corinne und Sandra Döller müssen wir die Fotocredits noch vermerken in der rechten Infospalte

**Comment by jensschnitzler** [comment]
wie soll das gestalterisch umgesetzt werden? ich lege dann noch ein feld fürs backend ein, das dann dort dargestellt wird, wenn es nicht leer ist.

**Comment by jensschnitzler** [comment]
Das Feld "Image Credits" sollte nach dem nächsten Upload im Interview im Panel verfügbar sein und als erster Punkt in der Liste unter dem Interviewbild ausgegeben werden.

**Comment by silvabaum** [comment]
sehr gut!

**Comment by silvabaum** [comment]
funktioniert!

@leasievertsen, ich konnte bei den meisten keine Credit-Angaben finden, die stehen glaube ich meist in den Mail. Könntest du die bitte einfügen?

@claudiascheer und @leasievertsen: was wollen wir davor schreiben? Credits: ? © (alt + G)?

**Comment by claudiascheer** [comment]
ich würds einfach so schreiben:
Credits: Max Mustermann

**Comment by leasievertsen** [comment]
Ja, das suche ich raus.

**Comment by leasievertsen** [comment]
alle credits die wir haben sind drin.
