### ISSUE TITLE
Themen als »Home-Button«

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#104]
Wenn ich mich in die Topics reingeklickt habe und diverse Antworten ausgeklappt sind, und ich dann auf Themen klicke, sollen sich dann alle Punkte einfahren und ich habe wieder die Ausgangs-Topic-Seite?

**Comment by jensschnitzler** [comment]
so hatte ich es verstanden, als eine möglichkeit schnell alles aufzuräumen …

**Comment by claudiascheer** [comment]
genau, das funktioniert bei mir leider noch nicht (firefox)

**Comment by jensschnitzler** [comment]
hmhm kann den fehler nicht nachstellen … hast du deinen cache mal geleert?

**Comment by leasievertsen** [comment]
Bei mir im Chrome funktioniert das gut.

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**

**Comment by silvabaum** [comment]
funktioniert in Chrome, Firefox und Safari
