### ISSUE TITLE
Interview Overlay: via Mail

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#105]
Ist nur eine Kleinigkeit: wenn die Mails per Mail geführt wurden, dann ergibt sich folgendes Problem. Kann man das einfach manuell ändern?  

![bildschirmfoto 2017-11-28 um 13 21 55](https://user-images.githubusercontent.com/33512565/33319542-6dfd50f6-d43f-11e7-9498-dd7e7849c237.png)

**Comment by jensschnitzler** [comment]
Was soll in diesem Fall denn angezeigt werden? Nur das "in" weg?

EDIT: issues bitte labeln und assignen, damit sie nicht untergehen.

**Comment by claudiascheer** [comment]
… wurde am [Datum] via E-Mail geführt.

**Comment by claudiascheer** [comment]
… wurde am [Datum] via E-Mail geführt.

So? Wir haben hier ja keinen Ort. Das gleiche gilt bei »via Skype«

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**

**Comment by claudiascheer** [comment]
klappt!
