### ISSUE TITLE
allgemein: Trennungen

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#106]
Kleinigkeit: die Trennungen sind manchmal noch falsch, ist das eine grundsätzliche oder manuelle Einstellung? > nice to have

![bildschirmfoto 2017-11-28 um 14 08 37](https://user-images.githubusercontent.com/33512565/33321382-c71042f6-d445-11e7-9c79-1cf4716cfd1e.png)

**Comment by jensschnitzler** [comment]
das können wir grundsätzlich übers css einigermaßen lösen.

_notiz an mich selbst:_ 
https://www.mediaevent.de/css3-silbentrennung-hyphens/

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen por favor.

**Comment by claudiascheer** [comment]
Jens hat schon neu geuploaded oder? Ich hab hier grad das entdeckt:
![bildschirmfoto 2017-11-30 um 14 26 41](https://user-images.githubusercontent.com/33512565/33433337-7c1faf9c-d5db-11e7-9475-2923c3d4d90b.png)

Falls Jens noch nicht geuploadet hat, bitte ignorieren ^^

**Comment by claudiascheer** [comment]
![bildschirmfoto 2017-11-30 um 14 34 55](https://user-images.githubusercontent.com/33512565/33433387-aa8182a2-d5db-11e7-98d0-19be3eea08e2.png)

etc. ;)

**Comment by silvabaum** [comment]
Jens sagt, die Seite muss noch auf Deutsch gestellt werden, dann sollte es gehen. ich Close es erst mal
