### ISSUE TITLE
Interview-Overlay, Fragen nicht Alternative Questions

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#108]
Aktuell werden im Interview die Fragen nicht die Alternative Questions im Singular angezeigt, sondern die "normalen" plural Fragen.

**Comment by silvabaum** [comment]
Beispiel:

![bildschirmfoto 2017-11-30 um 00 11 51](https://user-images.githubusercontent.com/33488569/33404066-2fb5f24c-d563-11e7-8ff3-5e7226029949.png)

**Comment by jensschnitzler** [comment]
ohlala, ich glaube, @otcn vlt weisst du es besser, dass die situation wie folgt ist:

- im blueprint _frage.yml_ bzw. im panel unter _themen/fragen_ können zwei fragen angelegt werden:
-- **title-Frage**: Question (plural, for navigation and interviews with multiple interviewees)
-- **alternative-Frage**: Alternative Question (singular, for interviews with only one interviewee)
- im panel kann im interview unter dem _label: Question Catalogue_ eine frage aus dem dropdown menü ausgewählt werden. die auswahl des dropdowns wird gespeist durch die _title_ der _themen/fragen_, also pluralfragen. 
- das blueprint _interview.yml_ , bzw. blueprints im allgemeinen, sind statische dateien, man kann also dort nicht etwa sagen "wenn es sich um ein interview mit nur einem interviewpartner handelt, verwende bitte in dem dropdown stattdessen bitte die _alternative frage_ .
- das heisst, die interview-datei, die nach eingabe im panel abgespeichert wird (wie z. B. _1-grafikladen/interview.txt_) enthält immer die plural _title-Frage_, das lässt sich soweit meine kenntnisse die diagnose zulassen, nicht vermeiden.
- um jetzt aber trotzdem ggf. die alternative-frage auszuspielen müsste im frontend (_interview.php_) bei der ausgabe eines interviews …
-- … abgefragt werden, ob es sich um mehrere interviewpartner handelt (_interviewpartner==true_)
--… und falls dies nicht der fall ist, müsste jede individuelle frage (aus der jeweiligen _interview.txt_, die gerade ausgespielt wird) mit jedem _title_ aus den _themen/fragen_ verglichen werden und wenn sie gleich sind, die _alternative_ dargestellt werden.

@otcn gibts einen besseren weg? das kommt mir irgendwie wie eine anfällige lösung um drei ecken vor …

**Comment by otcn** [comment]
Hey @jensschnitzler 
Ich weiß nicht., ob sich daran mittlerweile etwas geändert hat, aber wir haben ja eigentlich ins Panel eine Checkbox gebaut, mit der man angeben kann, ob es sich um einen bzw. mehrere Interviewpartner handelt. Und eigentlich hat da ja auch schonmal funktioniert. Hast du daran nochmal was geändert? 

Ansonsten müsste man mal schauen, ob durch einen anderen Fix an der Stelle etwas kaputt gegangen ist.

**Comment by jensschnitzler** [comment]
@otcn die checkbox ist noch da, aber an welcher stelle wird der bezug "ungecheckte checkbox = alternative Frage"  hergestellt?

**Comment by jensschnitzler** [comment]
mit diesem code konnte ich jetzt schon mal zwischen singular und plural interviews differenzieren:

```
<?php
if ($interview->interviewpartner() == '1') :
  $singleInterviewee = false; // interview was conducted with more than one interviewee
else :
  $singleInterviewee = true; // interview was conducted with only a single interviewee
endif;
echo '<script>console.log("' . $interview->title() . ' is singular: ' . $singleInterviewee . ' ")</script>';
?>
```

…

```
      <?php
      if ( $singleInterviewee ) :
        echo "Singular:";
        echo $interviewpart->frage()->kirbytext();
      else :
        echo "Plural:";
        echo $interviewpart->frage()->kirbytext();
      endif;
      ?>
```

**Comment by otcn** [comment]
Ist verschütt gegangen.
/site/templates/_archive/interview.php (es müsste der foreach loop Zeile 16-39 sein)

**Comment by jensschnitzler** [comment]
ah cool danke, dann versuch ich das einzubauen :-)

**Comment by otcn** [comment]
<3

**Comment by jensschnitzler** [comment]
👍 sollte mit dem nächsten upload funktionieren

**Comment by claudiascheer** [comment]
bei mir funktioniert es leider noch nicht, es kommen grundsätzlich die pluralfragen (firefox, safari, chrome)

**Comment by silvabaum** [comment]
ist auch noch nicht geuploaded, Jens schreibt dann in den Facebook-chat, wenn er es hochgeladen hat

**Comment by silvabaum** [comment]
funktioniert! 

Einige Fragen werden nicht angezeigt, aber ich habe gerade festgestellt, dass die scheinbar im Panel auf invisible sind (keine Ahnung warum), also kann ich das fixen.

**Comment by silvabaum** [comment]
Könnte das auch der Grund sein für Issue #55? Die meisten der Spezialfragen waren invisible. Vielleicht konnten sie deshalb nicht im Overlay gefunden werden?
