### ISSUE TITLE
Intro-Overlay lässt sich nicht schließen

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#109]
Habe die Seite gerade in drei Browsern getestet.
Chrome funktioniert super.
In Firefox und Safari taucht der gleiche Fehler auf: Die Nav. ist nicht ausgegraut und es gibt kein Schließsymbol und die Namensleiste wiederholt sich nicht. 

Zwei Screenshots zum Vergleichen
<img width="1440" alt="bildschirmfoto 2017-11-28 um 21 23 55" src="https://user-images.githubusercontent.com/33448884/33342602-f7717842-d482-11e7-9024-d2d54aa257ce.png">
<img width="1440" alt="bildschirmfoto 2017-11-28 um 21 24 27" src="https://user-images.githubusercontent.com/33448884/33342603-f79a4c18-d482-11e7-95b8-e38f840cf025.png">

**Comment by silvabaum** [comment]
Bei mir funktioniert es in allen drei Browsern. Lea, vielleicht Cache leeren und noch mal testen?

**Comment by leasievertsen** [comment]
Ich habe Firefox ganz neu dafür runtergeladen..

**Comment by leasievertsen** [comment]
ja aber gut, jetzt funktioniert es bei mir in beiden plötzlich auch.. ich close erstmal und werde das beobachten ;)

**Comment by silvabaum** [comment]
Ok, gut
