### ISSUE TITLE
Nav: Gleiche Frage wird mehrmals (mit jeweils anderer ID) aufgeführt

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#110]
Ein Problem, das in Verbindung steht mit issue #90 :

Gleiche Fragen werden mehrmals (mit jeweils anderer ID) in der Navigationaufgeführt.
In der Topics-Liste sind die Fragen (richtiger Weise) nur einmal vorhanden.
Nur eine der Fragen aus der Nav verweist auf die richtige ID der Frage in der Topic-Liste.

In der Topic-Liste hat unsere Frage die ID f36:

![bildschirmfoto 2017-11-28 um 23 46 46](https://user-images.githubusercontent.com/14975858/33348615-551d48c2-d497-11e7-9ead-9638b6cbd800.png)

Eine Frage in der Nav verweist falsch auf ID f61:

![bildschirmfoto 2017-11-28 um 23 47 54](https://user-images.githubusercontent.com/14975858/33348616-5534cf06-d497-11e7-9392-a7fedfbe403b.png)

Eine gleiche Frage verweist richtig ID f36:

![bildschirmfoto 2017-11-28 um 23 49 11](https://user-images.githubusercontent.com/14975858/33348617-554a9872-d497-11e7-8196-76661ddebb44.png)

Beim klick auf die ID f61 Frage passiert nichts.
Beim klick auf die ID f36 Frage scrollt es zur richtigen Frage in der Topic List.

**Comment by jensschnitzler** [comment]
👍 ich glaube ich habe es gefixt. checkt es nach dem nächsten update mal aus und testet, schließt, etc, merci

**Comment by leasievertsen** [comment]
Bei mir wiederholt sich nichts mehr! (chrome)

**Comment by silvabaum** [comment]
fixed!
