### ISSUE TITLE
Startseite in chrome

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#111]
Seit dem neusten Update ist bei mir in Chrome beim Aufrufen der Seite unter dem Interview-Overlay schon die Fragen-Nav ausgeklappt und ich kann nicht in den weißen Bereich klicken, also das Intro-Overlay verlassen.

![bildschirmfoto 2017-11-28 um 23 29 20](https://user-images.githubusercontent.com/33488569/33364660-a9884878-d4e5-11e7-98d5-c6a72b9ce0a9.png)

**Comment by silvabaum** [comment]
Und in Firefox sieht es so aus:

![bildschirmfoto 2017-11-29 um 09 31 28](https://user-images.githubusercontent.com/33488569/33368140-21d77d70-d4f1-11e7-8b9a-09319eb81b1a.png)

Manchmal geht der Overlay von alleine weg, manchmal nicht.

**Comment by claudiascheer** [comment]
bei mir sieht die Startseite so aus und ich kann leider gar nichts klicken (nach Firefox-Update)
![bildschirmfoto 2017-11-29 um 13 34 00](https://user-images.githubusercontent.com/33512565/33375392-0bf70106-d50a-11e7-8634-5c0700da367b.png)

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen, bitteschön.

**Comment by leasievertsen** [comment]
bei mir geht gerade chrome gut, in firefox wird die leiste noch nicht richtig angezeigt

<img width="1440" alt="bildschirmfoto 2017-11-29 um 22 56 55" src="https://user-images.githubusercontent.com/33448884/33401189-bfc5d696-d558-11e7-8527-cd9a1cd5c08a.png">

**Comment by silvabaum** [comment]
bei mir wird in Chrome, Firefox und Safari alles korrekt angezeigt

**Comment by claudiascheer** [comment]
Jetzt klappt bei mir im Chrome, Firefox und Safari auch alles gut!
