### ISSUE TITLE
NAV: Button "EN"

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#112]
Was soll mit dem Button passieren, da ja absehbar ist, dass englisch beim launch nicht verfügbar sein wird. soll der button erstmal ausgeblendet werden oder soll, wie jetzt, eine error message erscheinen? falls letzteres, was soll in der nachricht stehen?

**Comment by claudiascheer** [comment]
Ich fände es gut, wenn eine error message erscheint, damit die Leute wissen, dass das noch kommt und wir dran arbeiten? eine fehlermeldung und dann noch sowas wie we are working on it! oder so?

**Comment by silvabaum** [comment]
finde ich auch gut! vielleicht: "Sorry, english isn't available yet, but we are working on it!", @claudiascheer @leasievertsen?

**Comment by claudiascheer** [comment]
Ja genau!

**Comment by silvabaum** [comment]
@jensschnitzler, wir haben eine Lösung: Bitte nicht ausblenden und Hinweis: "Sorry, English isn't available yet, but we are working on it!" einfügen

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen, bitteschön.
