### ISSUE TITLE
Nav Interviews: Buchstabensortierung fehlt

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#113]
In der Interview-Navigation werden die Fragen richtig sortiert dargestellt, aber die Buchstaben vorne fehlen teilweise, siehe Screenshot (Firefox)

![bildschirmfoto 2017-11-30 um 14 29 40](https://user-images.githubusercontent.com/33512565/33433205-05aa7af4-d5db-11e7-960e-b4d3c97488a0.png)

**Comment by otcn** [comment]
Seltsam. Ich versuche gerade Issue #110 außerhalb des Seitenkontextes (also auf einer temporären Seite) zu lösen. Und auf dieser Seite gibt es kein Problem mit der Buchstabensortierung.

Scheint also eher am Umfeld zu liegen?

![bildschirmfoto 2017-11-30 um 14 40 39](https://user-images.githubusercontent.com/24541531/33433693-de20795a-d5dc-11e7-9788-95bf16115a98.png)

**Comment by jensschnitzler** [comment]
👍  da hat wohl die entscheidende zeile code gefehlt :-) sollte nach dem nächsten upload funktionieren. dann bitte testen und schließen, dankjewell

**Comment by silvabaum** [comment]
check!
