### ISSUE TITLE
Interview-Overlay, Christiane Funken: Doppelte Frage

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#114]
Im Interview von Christiane Funken (http://dev.notamuse.de/interviews/Christiane-Funken) wird eine frage doppelt aufgeführt und ich kann nicht nachvollziehen, woher das kommt. Vielleicht habt ihr eine Idee, @jensschnitzler oder @otcn?

![bildschirmfoto 2017-12-01 um 15 38 28](https://user-images.githubusercontent.com/33488569/33487564-e813b37e-d6ad-11e7-98e6-3f3f437324a9.png)

**Comment by otcn** [comment]
@jensschnitzler Hast du's schon gefixt? Ich kann's nämlich nicht reproduzieren (Safari 11.0.1 )

**Comment by silvabaum** [comment]
Bei mir ist es noch, auch in Chrome, Firefox und Safari, auch nachdem ich den Cache gelöscht habe

**Comment by jensschnitzler** [comment]
lokal kommt bei mir der fehler auch nicht vor, auf der dev seite jedoch schon …

ich habe in interview.php zwei geschweifte klammern in einem foreach loop hinzugefügt, vlt behebt das irgendwas :-D (Zeile 75)

```
        foreach($pages->find('themen')->grandchildren()->visible() as $frage) {
          if( strcasecmp($frage->title(), $interviewpart->frage() ) == 0) {
            echo $frage->alternative()->kirbytext();
          }
        }
```

bitte nach dem nächsten upload noch mal testen

**Comment by silvabaum** [comment]
Ist noch genauso

**Comment by jensschnitzler** [comment]
scheinbar hat silva das im panel korrigiert, sollten ähnliche fehler noch mal auf treten, kann das issue hier ja wieder eröffnet werden
