### ISSUE TITLE
Trennungen raus bei Interview-title, topic-titles und in der Nav

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#115]
Bitte die Trennungen wieder rausnehmen bei:

a.interviewee-title
.topic-title

und in der gesamten nav: sowohl die Buttons als auch die Inhalte sollten nicht umbrechen, damit sich die Zeilenlänge beim Hovern nicht verändert.

**Comment by jensschnitzler** [comment]
👍 das sollte nach dem kommenden upload funktionieren. test + close, please

**Comment by silvabaum** [comment]
`a.interviewee-title` umbricht bei mir noch:
![bildschirmfoto 2017-12-03 um 12 03 53](https://user-images.githubusercontent.com/33488569/33524828-10f085d4-d824-11e7-89e0-c4aef0cedc29.png)

`.sub a` in der nav umbrechen ebenfalls noch:
![bildschirmfoto 2017-12-03 um 12 23 32](https://user-images.githubusercontent.com/33488569/33524923-a3fe91c6-d825-11e7-8eda-a89a0f08c312.png)

**Comment by jensschnitzler** [comment]
👍 should be fixed. test and close plz

**Comment by silvabaum** [comment]
Die `a.interviewee-title` umbrechen bei mir leider immer noch.
`.sub a` ebenfalls, allerdings "schlängeln" die beim Hovern nicht mehr, daher wäre es so erst mal in Ordnung. 

(Die Bildbeispiele in meinem vorherigen Kommentar sehen noch genauso aus.)
