### ISSUE TITLE
aktive Navi verschiebt Content nicht nach rechts

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#117]
Wenn ich einen Punkt aus der Navi anklicke, verschiebt es den Content nicht mehr nach rechts (Firefox, Chrome, Safari). Hat noch jemand das Problem?

![bildschirmfoto 2017-12-01 um 18 24 51](https://user-images.githubusercontent.com/33512565/33494990-28274252-d6c5-11e7-90d9-128c203161e3.png)

**Comment by jensschnitzler** [comment]
👍  ist wohl beim hinzufügen des css codes für mobile passiert. sollte aber nach dem nächsten upload wieder funktionieren. dann bitte testen und schließen, dankjewell

**Comment by silvabaum** [comment]
Chrome, Firefox, Safari: check!
