### ISSUE TITLE
Intro-Overlay: Abstand nach unten

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#118]
Der Intro-nav bitte noch Padding nach unten geben. Wenn das Intro gescrollt wird, endet es gerade ohne Abstand zwischen "Alle Antworten zu dieser Frage" und unterem Seitenrand:

![bildschirmfoto 2017-12-02 um 19 16 19](https://user-images.githubusercontent.com/33488569/33518503-3f03046c-d796-11e7-9633-8723b1eb4b49.png)

Bitte ändern zu:
```
.intro-nav {
    position: relative;
    padding-top: 1rem;
    padding-bottom: 35px;
```

**Comment by jensschnitzler** [comment]
👍 das sollte nach dem kommenden upload funktionieren. test + close, please

**Comment by silvabaum** [comment]
check!
