### ISSUE TITLE
About-Overlay: Abstand zwischen Elementen

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#120]
Die Abstände im About-Overlay bitte wie folgt ändern:

`#about-content` soll nicht das gleiche Margin-bottom haben wie `#interview-content` und `#about-imprint`, sondern:
```
#about-content {
    max-width: 48vw;
    margin-bottom: 0vh;
```

Der Abstand darunter wird dann definiert durch nachfolgende h2:
```
.about-container h2 {
    margin-top: 115px;
```

Das Padding der network-liste entfällt:
```
.network-list {
    margin: 0 0 0 0;
    padding: 0 0 0 0;
```

**Comment by jensschnitzler** [comment]
👍 fixed it. test/close, please.
