### ISSUE TITLE
About-Overlay: Externen Links in der network-list fehlt Symbol

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#122]
Externe Links in der `.network-list`(`.overlay a`?) sollten sich wie 'normale' externe Links verhalten: Nord-Ost-Pfeil dahinter und Unterstreichung bei Hover:

Aktuelle Netzwerk-Liste:
![bildschirmfoto 2017-12-02 um 21 03 48](https://user-images.githubusercontent.com/33488569/33519282-60035140-d7a4-11e7-87b7-4f81bfb2b056.png)

Externe Links:
![bildschirmfoto 2017-12-02 um 21 05 37](https://user-images.githubusercontent.com/33488569/33519307-94e4de74-d7a4-11e7-81ce-c9191b5e68b5.png)

**Comment by jensschnitzler** [comment]
👍 fixed it. test/close, please.
