### ISSUE TITLE
About-Overlay: Email-Link hat Symbol von internen Links

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#123]
Ich habe im Impressum im About-Overlay die Mailadresse verlinkt (`<a href="mailto:hi@notamuse.de">hi@notamuse.de</a>`), dargestellt wird der Link nun mit einem Pfeil davor, wie sonst die internen Links. Schöner wäre es wenn er gar keinen oder den Pfeil danach, wie die externen Links, hätte.

Absolutes nice-to-have!

**Comment by jensschnitzler** [comment]
👍 fixed it. test/close, please.
