### ISSUE TITLE
Interview: Amanda Haas: Frage f83 wird nicht ausgegeben

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#124]
Mitten im Interview wird eine Frage nicht dargestellt, die aber in der interview.txt vorhanden ist. es handelt sich um eine spezialfrage, evtl hat es etwas damit zu tun …

![bildschirmfoto 2017-12-03 um 00 41 08](https://user-images.githubusercontent.com/14975858/33520834-c928b7dc-d7c2-11e7-832c-aa6a4c7de496.png)
<img width="1147" alt="bildschirmfoto 2017-12-03 um 00 41 17" src="https://user-images.githubusercontent.com/14975858/33520835-c941d10e-d7c2-11e7-9e2d-f01c4fe63bf5.png">

**Comment by otcn** [comment]
Hat sich Wohlgefallen aufgelöst. Testen und schließen, wenn es tatsächlich erledigt ist.
