### ISSUE TITLE
Nav: Abstände zwischen Buttons

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#126]
Die Abstände zwischen den Buttons in der Nav stimmen nicht mehr. Im Code habe ich gefunden, dass das Margin ausgeschaltet war, wenn es an ist, sieht alles wieder richtig aus:

```
.nav-container ul.nav li {
    padding: 0px 0px 0px 0px;
    margin: 0px 0px 7px 0px;
```

falsch:
![bildschirmfoto 2017-12-03 um 13 23 38](https://user-images.githubusercontent.com/33488569/33525307-35f72d02-d82d-11e7-99c0-8513d859b948.png)

richtig:
![bildschirmfoto 2017-12-03 um 13 23 12](https://user-images.githubusercontent.com/33488569/33525308-44f6184a-d82d-11e7-9a45-24612791810b.png)

**Comment by jensschnitzler** [comment]
👍 fixed. test + close, plz
