### ISSUE TITLE
Nav: Hover-Pfeil vor Listenelementen

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#129]
Der Pfeil, der beim Hovern über die Listenelemente in der Nav vor den Elementen erscheint, verdeckt die Ordnungsbuchstaben noch nicht vollständig.

![bildschirmfoto 2017-12-03 um 16 21 35](https://user-images.githubusercontent.com/33488569/33526780-41804910-d846-11e7-85bb-51ba69f82775.png)

**Comment by jensschnitzler** [comment]
👍 fixxeed
