### ISSUE TITLE
Questions -> Answers umbrechen falsch

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#132]
Bei mir umbrechen die Fragen wieder falsch, also nicht da wo sie, wenn sie angewählt werden, sollen, sondern "irgendwo". Teilweise werden sie auch vom Banner überlagert. Tritt auf in Chrome und Safari. Das war auf jeden Fall vorher schonmal gefixt.
<img width="1440" alt="bildschirmfoto 2017-12-03 um 22 59 33" src="https://user-images.githubusercontent.com/33448884/33530453-e5ab2a26-d87f-11e7-8031-2f2e5ea73098.png">

**Comment by claudiascheer** [comment]
Das Gleiche passiert im Firefox

**Comment by silvabaum** [comment]
@jensschnitzler, hängt vermutlich auch mit der Bearbeitung der Mobileversion zusammen. 
Ebenso wie #136

**Comment by jensschnitzler** [comment]
👍 war ein fehler der sich gestern beim aufräumen des css und der bearbeitung des css für mobile eingeschlichen hatte. sollte nachd em nächsten upload wieder richtig sein.

**Comment by silvabaum** [comment]
check!
