### ISSUE TITLE
Interview Overlay: Größe Einleitungstext

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#133]
Der Einleitungstext ist gerade nicht mehr größer sondern genauso groß wie das Interview. 
@silvabaum habt ihr das entschieden oder ist das unabsichtlich? Ich finde es jetzt gar nicht so schlecht, wollte es nur sicherheitshalber anmerken.

<img width="1440" alt="bildschirmfoto 2017-12-03 um 23 01 08" src="https://user-images.githubusercontent.com/33448884/33530467-244893e0-d880-11e7-85b0-55ae41924462.png">

**Comment by silvabaum** [comment]
Hängt vermutlich zusammen mit #135 und #136

**Comment by jensschnitzler** [comment]
👍  war ein fehler der sich gestern beim aufräumen des css und der bearbeitung des css für mobile eingeschlichen hatte. sollte nachd em nächsten upload wieder richtig sein.

**Comment by silvabaum** [comment]
check!
