### ISSUE TITLE
Interview Overlay: Nachname läuft unter Bild durch

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#134]
siehe Screenshot: (Firefox)

![bildschirmfoto 2017-12-04 um 09 47 06](https://user-images.githubusercontent.com/33512565/33543717-53d28cf8-d8d8-11e7-8dac-2e69521e16d6.png)

**Comment by silvabaum** [comment]
@jensschnitzler, ich habe versucht dort einen bedingten Trennstrich mit `&shy;` einzubauen. Im Overlay wird dann aber &shy; als Text ausgegeben. Das gleiche ist auch mit anderen Varianten passiert, die ich recherchiert hatte (z.B. `<code>&amp;shy;</code>`).
Wenn ich das gleiche z.B. bei der Einleitung eingebe, wird es wie gewünscht als Trennstrich ausgegeben. 

![bildschirmfoto 2017-12-04 um 12 06 57](https://user-images.githubusercontent.com/33488569/33549691-ae6fd00e-d8eb-11e7-883d-f858ee7d17d7.png)

**Comment by jensschnitzler** [comment]
👍  sollte nach dem nächsten upload wieder richtig sein.

**Comment by silvabaum** [comment]
check!
