### ISSUE TITLE
Intro-Overlay: Intro-Quote, Intro-Nav Schriftgröße

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#135]
Scheinbar wurden bei den Änderungen für Mobile auch Sachen in der Desktop-Version geändert:
Auf dem Intro-Overlay werden **Intro-Quote** und **Intro-Nav** in der kleinsten Schriftgröße ausgegeben, sie sollten in der _Desktop-Version_ aber die _mittlere Schriftgröße_ haben.

![bildschirmfoto 2017-12-04 um 09 43 45](https://user-images.githubusercontent.com/33488569/33543726-5f44ed2e-d8d8-11e7-80f4-f64a59b81f76.png)

**Comment by jensschnitzler** [comment]
👍 war ein fehler der sich gestern beim aufräumen des css und der bearbeitung des css für mobile eingeschlichen hatte. sollte nachd em nächsten upload wieder richtig sein.

**Comment by silvabaum** [comment]
check!
