### ISSUE TITLE
Main-Layer: question-title Schriftgröße

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#136]
Ähnliches Problem wie in Issue #135: Die **question-titles**, die auf dem Desktop eigentlich in der _mittleren Schriftgröße_ sein sollten, werden in der kleinsten Schriftgröße dargestellt.

**Comment by jensschnitzler** [comment]
👍  should be fixed after next upload. please test and close

**Comment by silvabaum** [comment]
check!
