### ISSUE TITLE
Intro: »Alle Antworten auf diese Frage« funktioniert nicht 

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#138]
Wenn ich im Intro auf »Alle Antworten auf diese Frage« klicke, komme ich nur zu den Topics

**Comment by claudiascheer** [comment]
*im

**Comment by jensschnitzler** [comment]
@claudiascheer du kannst kommentare im nachhinein bearbeiten ;-) –––––––––––––––––––––––––↑

**Comment by jensschnitzler** [comment]
👍  das feature hatten wir wohl scheinbar gestern zerschossen, sollte jetzt aber wieder funktionieren. test & close

**Comment by silvabaum** [comment]
check!
