### ISSUE TITLE
Mobile: Intro nicht scrollbar

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#139]
Wenn das Zitat auf dem Startscreen länger ist, kann ich es nicht nach unten scrollen

**Comment by jensschnitzler** [comment]
@claudiascheer funktioniert bei mir. kannst du nochmal testen?

notiz an mich selbst:

```
overflow: scroll;
-webkit-overflow-scrolling: touch;
```

**Comment by claudiascheer** [comment]
@jensschnitzler bei mir am Handy funktioniert das Scrollen leider noch nicht, ich kann die rote Fläche dann nicht nach unten scrollen und das Intro nur über das Kreuz verlassen

**Comment by jensschnitzler** [comment]
bitte nach dem nächsten upload noch mal testen und dann 
-> entweder wieder mir zuweisen und das labeln "test" entfernen
-> oder schließen

**Comment by silvabaum** [comment]
geht
