### ISSUE TITLE
Mobile: Burger/Close Symbol zu groß

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#140]
Burger und Close-Symbol im Header sind zu groß

**Comment by jensschnitzler** [comment]
@claudiascheer wie groß soll es sein? kannst du vlt sogar übers untersuchen-tool herausfinden, wie das css richtig sein müsste? falls nicht, kein problem!

**Comment by claudiascheer** [comment]
@jensschnitzler im Entwurf haben wir es so hoch wie die x-Höhe des Logos und bündig mit der Grundlinie, siehe Screenshot. Kannst du damit was anfangen oder soll ich noch was rausfinden irgendwie? ;)

![bildschirmfoto 2017-12-05 um 16 36 30](https://user-images.githubusercontent.com/33512565/33615565-c55944cc-d9da-11e7-99d6-ff5b3efcbc3f.png)

![bildschirmfoto 2017-12-05 um 16 36 46](https://user-images.githubusercontent.com/33512565/33615566-c578a286-d9da-11e7-9006-34f23291d2f9.png)

**Comment by jensschnitzler** [comment]
danke! das sollte als angabe reichen :-)

notiz an mich selbst:

x-höhe 19px
![bildschirmfoto 2017-12-05 um 16 57 21](https://user-images.githubusercontent.com/14975858/33616662-d04598a6-d9dd-11e7-8265-a1182ca9c2d7.png)

**Comment by jensschnitzler** [comment]
👍  größe des burgers ist in mobile jetzt besser. nach nächsten upload bitte testen und schließen, danke
