### ISSUE TITLE
Mobile: Burger lässt sich nicht öffnen

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#141]
das Burgermenü lässt sich nicht öffnen

**Comment by jensschnitzler** [comment]
@claudiascheer bitte immer jemand assignen, sonst geht das ticket unter :-)

**Comment by otcn** [comment]
Scheint ja mittlerweile zu funktionieren.
@jensschnitzler Ich häng hier mal das Test-Label dran!?

**Comment by claudiascheer** [comment]
ja, klappt super!
