### ISSUE TITLE
Mobile: Padding answer-item

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#147]
Die Antworten sollten nach rechts ein _padding von 4vw_ haben.
Ich weiß nicht welchem Element genau du das padding geben möchtest, im Untersuchen-tool habe ich es hier geändert:

```
@media (max-width: 768px)
style.css:1511
#content ul.topic-list .topic-item .question-list .question-item .answer-list .answer-item {
    padding: 2vh 4vw;
```

**Comment by jensschnitzler** [comment]
👍  padding ist in mobile jetzt besser. nach nächsten upload bitte testen und schließen, danke
