### ISSUE TITLE
Mobile: Scrollverhalten

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#148]
Mobile scrollt noch nicht "schön": Text läuft beim swipen nicht weiter, sondern stoppt, sobald man Bildschirm nicht mehr berührt.
@zweipi hatte dafür gestern schon eine Lösung, die ich aber nicht mehr weiß.

**Comment by otcn** [comment]
@silvabaum Sollte funktionieren

EDIT: Ah, sorry – ist doch noch nicht gut. Ich schau nochmal

**Comment by jensschnitzler** [comment]
hat es etwas hiermit zu tun?
```

overflow: scroll;
-webkit-overflow-scrolling: touch;
```

**Comment by otcn** [comment]
Also  das `-webkit-overflow-scrolling: touch` macht, das der Container schmoof scrollt. Das hab ich gestern Abend eingebaut. Was gerade noch doof ist: Dadurch kann man den Inhalt momentan noch scrollen, auch wenn das Intro-Overlay drüber liegt. Dazu bin ich noch nicht gekommen.

**Comment by jensschnitzler** [comment]
@otcn meinst du mit eingebaut, auf github gepusht oder mit ftp auf den live server geladen? falls letzteres: es gibt seit gestern abend übergangsweise eine notlösung bzgl der zweisprachigkeit:

- auf dem server im ordner /_dev-de/ liegt eine kopie der website für die deutschsprachige variante der website. die subdomain ist zu erreichen unter [de.notamuse.de](http://de.notamuse.de/) ODER dev.notamuse.de - beide verlinken auf die gleichen inhalte.
- auf dem server im ordner /_dev-en/ liegt eine kopie der website für die eglischsprachige variante der website. die subdomain ist zu erreichen unter [en.notamuse.de](http://en.notamuse.de/)

@silvabaum  macht es sinn dazu irgendwas irgendwo zu dokumentieren, um zu erklären, dass es jetzt zwei panels gibt usw?

Das heisst: änderungen am code müssen in beide ordner hochgeladen werden

**Comment by otcn** [comment]
@jensschnitzler Nur gepusht

**Comment by jensschnitzler** [comment]
@claudiascheer  könntest du es nach dem nächsten upload noch mal testen? wüsste gerade nicht, welche optimierung für besseres scrollverhalten noch vorgenommen werden könnten :-(
