### ISSUE TITLE
Englische Version der ganzen Seite

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#149]
@zweipi, @jensschnitzler, @otcn, die englischsprachige Version der Seite gewinnt gerade immer mehr an Stellenwert, weil immer mehr internationale Plattformen (z.B. AIGA) Interesse zeigen und unseren Launch bewerben wollen. Wie groß ist der Aufwand die englische Seite zu machen, bzw. bis wann könnten wir es schaffen, die englische Variante zu launchen?

Wir sind da mit den Interviews auch noch nicht fertig, aber ich hätte gerne eine Einschätzung, ob es irgendwie möglich wäre, das relativ zeitnah zu schaffen.

**Comment by janareddemann** [comment]
Ich habe es eben mal getestet und leider klappt es über den Weg, den man eigentlich gehen würde, nicht gut. Ich bin auch zu wenig in eurem Code drin, um genau zu sagen, wo es harkt.  
Realistisch nimmt es daher schon ziemlich viel Zeit ein, die ich gerade leider nicht zur Verfügung habe ...  
Wenn ihr jetzt aber ganz flott eine englische Version haben wollt, könntet ihr eigentlich die ganze Seite klonen und nochmal selbständig laufen lassen. Das ist zwar nicht besonders komfortabel, aber dann „nur noch“ Fleissarbeit beim Einpflegen.  
Die zweite Seite könnte entweder auf einer eigenen Domain laufen (notamuse.com etc.) oder ihr legt eine Subdomain an (en.notamuse.de).  
Wäre das für euch eine Alternative?

**Comment by silvabaum** [comment]
Danke für die schnelle Antwort! 
So eine Subdomain hat Jens gestern noch angelegt, wir waren nur nicht sicher wie viel Mehraufwand es gewesen wäre, es "richtig" zu machen. Aber dann vertagen wir das und überlegen ob wir schon vorher mit en.notamuse.de online gehen.
