### ISSUE TITLE
Panel: Interview: Answer: Internal and External Links

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#15]
Hi!

Wie kann man bei der Eingabe einer Interview-Antwort Text als internen oder externen Link markieren? Also so, dass dem markierten Textabschnitt je nachdem die class "a-extern" oder "a-intern" vergeben wird?
Das ist wahrscheinlich notwendig, weil sie unterschiedlich ausgezeichnet werden (siehe Dropbox/…/_notamuse-material/171002_Web_NEU.indd).

**Comment by otcn** [comment]
![1](https://user-images.githubusercontent.com/24541531/32245117-085399ce-be7b-11e7-8f32-d264c154babc.png)
![2](https://user-images.githubusercontent.com/24541531/32245119-0870d2d2-be7b-11e7-9994-5eaf972f9f95.png)

**Comment by janareddemann** [comment]
Hey,

ihr könnt alternativ auch über jquery abfangen, was ein externer Link ist:

```
  function externalLinks() {
      $('a').each(function(){
        if ($(this).attr('href') && $(this).attr('href').match(/https?:\/\/(?!localhost)/)) {
          $(this).attr('target','_blank').addClass('e-link')
        }
      })
  };

  externalLinks();
```

**Comment by jensschnitzler** [comment]
Works :-)
