### ISSUE TITLE
main-layer: Linie unter answer-list

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#150]
Hallo @jensschnitzler, könntest du relativ kurzfristig eine (glaube ich) kleinen Änderung vornehmen?

Unter der letzten Antwort zu einer Frage im Main-Layer fehlt die border-bottom.
Wenn ich die hier ausschalte, ist sie wieder da:
```
#content ul.topic-list .topic-item .question-list:last-child .answer-list {
    /* border-bottom: 0px; */
```
Allerdings weiß ich nicht, ob sie dann irgendwo anders fehlt.

Darunter ist noch folgende Code, der dann vermutlich wieder gilt, wenn die border-bottom oben ausgeschaltet wird:
```
#content ul.topic-list .topic-item .question-list, #content ul.topic-list .topic-item .answer-list {
    padding: 0;
    border-bottom: 1px solid #000;
    border-top: 1px solid #000;
```

**Comment by jensschnitzler** [comment]
👍  die linie sollte wieder da sein. nach dem nächsten upload bitte: testen + schließen
