### ISSUE TITLE
Main-Layer: Sticky Frage scrollt über Topic

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#151]
**Situation:** Im Main-Layer sind ein topic und eine Frage active und sticky. Die Antworten werden druchgescrollt. Am Ende der Antwortenliste folgen die weiteren Fragen. Wenn die bei der aktiven Frage sind, verliert dies ihre sticky-Position und scrollt mit den anderen weiter nach oben.
**Bug:** Die _aktive Frage_ scrollt nicht _unter_ dem Thema durch, sondern _darüber_:

![bildschirmfoto 2017-12-05 um 10 37 11](https://user-images.githubusercontent.com/33488569/33600334-372d1772-d9a9-11e7-9a32-9674f96d098f.png)

Die anderen, nicht aktive, Frage gehen, wie gewollt, darunter.

**Comment by jensschnitzler** [comment]
@silvabaum schalte mal deine autokorrektur aus :-D

**Comment by jensschnitzler** [comment]
👍  die z-indexe sind jetzt wieder richtig. nach dem nächsten upload bitte: testen + schließen
