### ISSUE TITLE
Mobile: Burger-Menü geht nicht mehr weg

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#152]
Ich rufe die Seite übers Handy auf, öffne das Burger-Menü und wähle darin etwas aus (zB. ein Interview oder die About-Seite), dann lädt sich die gewünscht Seite zwar, liegt aber unter dem Burger-Menü, so dass ich sie nicht sehen kann > das geöffnete Menü geht nicht weg und liegt über den Inhalten

**Comment by jensschnitzler** [comment]
@claudiascheer was soll stattdessen passieren? soll sich das menü direkt schließen sobald du zB auf "about" getippt hast? oder soll sich das menü erst schließen, wenn du oben rechts auf das kreuz getippt hast?

@claudiascheer @leasievertsen  @silvabaum  werft gerne mal einen blick in diesen kommentar (oder irgend einen anderen auf google) zum thema github issues: https://upthemes.com/blog/2014/02/writing-useful-github-issues/

**Comment by claudiascheer** [comment]
@jensschnitzler ohje sorry, ich gelobe besserung!!

Also da das Menü manchmal viel länger ist als der Screen (zB bei den Interviews) sieht man ja nicht, ab wann die Seite drunter geladen ist, deswegen würde ich die Variante wählen, in der sich das Menü direkt schließt, nachdem die Inhalte drunter geladen wurden

**Comment by jensschnitzler** [comment]
👍  die mobile nav schließt sich jetzt durch tippen auf about, en, eine frage oder einen interview-link. nach dem nächsten upload bitte: testen + schließen
