### ISSUE TITLE
Mobile: Pfeile weiß hinterlegt in Nav-Liste

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#154]
Mobile: Pfeile weiß hinterlegt in der Nav-Liste

![img_8363](https://user-images.githubusercontent.com/33512565/33609935-39e0ddca-d9ca-11e7-880d-814fe0435a69.PNG)

**Comment by jensschnitzler** [comment]
wie sollen denn die sub-menü punkte für interviews und fragen auf mobile aussehen? das pdf enthält dazu keinen entwurf. eigentlich brauchts da die pfeile gar nicht, oder? (die pfeile erscheinen ja nur bei hover auf das dazugehörige listenelement)

[20171122_Mobile_cs.pdf](https://github.com/otcn/notamuse/files/1531569/20171122_Mobile_cs.pdf)

**Comment by claudiascheer** [comment]
ja du hast recht, die pfeile machen mobil auch nicht wirklich sinn! pfeile einfach weglassen, A/B/C/… vielleicht einrücken, dass alles linksbündig ist und den kleinen Abstand lassen, der grad eh schon zwischen den Namen ist, fände ich gut!

**Comment by jensschnitzler** [comment]
👍  pfeile werden mobil nicht mehr dargestellt. nach nächsten upload bitte testen und schließen, danke
