### ISSUE TITLE
Uta Brandes: Frage fehlt im Interview, Antwort wird angezeigt

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#157]
Zufällig bei Uta drauf gestoßen: im Interview wird nicht die Frage, sondern nur die Antwort angezeigt. Aus Zeitdruck hab ich die Stelle grade noch nicht im Panel angeguckt – ein Issue, dass der Punkt nicht verloren geht

![bildschirmfoto 2017-12-07 um 10 55 19](https://user-images.githubusercontent.com/33512565/33709461-c646c3be-db3d-11e7-9a08-c4e6f59076e4.png)

**Comment by janareddemann** [comment]
Das liegt anscheinend an den &shy; im Titel. Wenn das raus ist, wird die Frage wieder angezeigt ...

**Comment by silvabaum** [comment]
fixed, war nicht richtig zugeordnet
