### ISSUE TITLE
en.notamuse.de: Nav und Intro-Nav übersetzen

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#158]
Bitte in der englischen Version die Nav-buttons "Themen" und "Fragen" ändern in "Topics" und "Questions"; 
"EN" in "DE" ändern

Die Intro-Nav bitte ändern in "All answers to this question" und "All topics at a glance" ändern

**Comment by jensschnitzler** [comment]
bitte mal unter dev.notamuse.de testen und ggf ticket schließen
