### ISSUE TITLE
"Questions" aktualisieren

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#16]
Hi @jensschnitzler, @otcn! Beim testen ist mir aufgefallen, dass wir nicht die aktuellste Version des Fragenkatalogs online haben, das müsste aktualisiert werden, bzw. könnten wir das selber machen?

**Comment by jensschnitzler** [comment]
Hi @leasievertsen, wenn ich das richtig verstehe, könnt ihr das im panel machen.
Im Screenshot bin ich im Panel unter Themen>Prozesse und in der linken Spalte werden unter der Überschrift "Pages" die Fragen aufgeführt, die diesem Thema untergeordnet sind.
Dort könnt ihr editieren, hinzufügen, löschen.
<img width="1237" alt="bildschirmfoto 2017-11-07 um 18 48 46" src="https://user-images.githubusercontent.com/14975858/32509041-7f3934d8-c3ec-11e7-83cf-687484bc6a1f.png">

**Comment by silvabaum** [comment]
Ich habe alle Themen und Fragen aktualisiert, allerdings könnte ich neu hinzugefügte Fragen noch nicht in den "visible"-Bereich ziehen. Sie springen immer wieder zurück in die rechte "invisible" Seite. Das gleiche passiert, wenn ich versuche die Reihenfolge durch verschieben zu ändern. Muss ich noch etwas anderes machen, außer die Frage in den anderen Bereich zu schieben?

**Comment by jensschnitzler** [comment]
hi @silvabaum , hi @otcn , problem behoben, das funktioniert jetzt! das problem war, dass ich im entsprechenden blueprint mit "options: status: false" verboten habe, dass du die frage auf "visible" stellst.
