### ISSUE TITLE
Mobile: Intro geht nicht weg

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#160]
Wenn ich mit dem Handy auf die Seite gehe, fehlt das Logo und der Close-Button, dh. ich bekomme das Intro nicht weg und damit nicht über die Startseite hinaus. 
![img_8451](https://user-images.githubusercontent.com/33512565/33887166-2d38a6f0-df49-11e7-90b9-435c11b8d496.PNG)

**Comment by jensschnitzler** [comment]
weirdweirdweird, ich kann diesen fehler nicht reproduzieren … könntet ihr das mal in verschiedenen browsern auf dem iphone testen? @leasievertsen  @claudiascheer @silvabaum

**Comment by jensschnitzler** [comment]
👍 sollte gelöst sein, bitte testen und schließen
