### ISSUE TITLE
Startseite "DE" statt "EN"

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#161]
Auf der Startseite steht "DE" statt "EN"..

<img width="1187" alt="bildschirmfoto 2017-12-14 um 20 06 20" src="https://user-images.githubusercontent.com/33448884/34009791-87fbcf5a-e10a-11e7-96be-69f97795be6c.png">

**Comment by jensschnitzler** [comment]
👍  sollte im nächsten upload gefixt sein
