### ISSUE TITLE
Nav: kaputte Spezialfragen 

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#167]
Hi @leasievertsen @silvabaum @claudiascheer 

- beim testen der englischen Seite ist mir aufgefallen, dass unter Navigation>Questions ein paar Spezialfragen schlecht oder gar nicht funktionieren.
- ich gehe davon aus, dass diese fehler behoben werden können, wenn ihr im panel im interview überprüft, ob die entsprechende frage wirklich als spezialfrage gecheckt ist und ggf muss man noch mal in der interview-unit die richtige frage und das richtige topic auswählen.
- wenn das nicht hilft gebt gerne noch mal bescheid.

**Comment by silvabaum** [comment]
Ich habe alle Fragen im Panel geprüft, bei manchen war die Übersetzung nicht mehr da. Noch mal testen!

**Comment by jensschnitzler** [comment]
eine englische spezialfrage die in der nav nicht funktioniert hat war gerade: 

<img width="373" alt="bildschirmfoto 2017-12-21 um 11 34 56" src="https://user-images.githubusercontent.com/14975858/34252218-01a2b0b6-e643-11e7-9d05-0a9c0aac9ccc.png">

**Comment by silvabaum** [comment]
fixed!

**Comment by silvabaum** [comment]
![bildschirmfoto 2017-12-21 um 12 55 51](https://user-images.githubusercontent.com/33488569/34254857-4fea9f30-e64e-11e7-9d75-f4dcd7b95bd5.png)
hat gerade nicht funktioniert, heißt: das Interview von Louise Fili wird geöffnet aber es springt nicht zur entsprechenden Stelle, sondern öffnet am Interviewanfang. Die checkbox ist angewählt und im Panel scheint alles ok zu sein. @jensschnitzler 

Update: 
Das gleiche passiert bei anderen Fragen an Louise Fili: 
Do you prefer working with men or women?
Do you think male and female designers interacted differently with each other during the 1970s and 80s?
Were you aware of taking a big step in becoming a female pioneer with opening your own studio in 1989?

Auch bei Fragen an Christiane Funken:
How can women like us push change …?

Manchmal funktioniert es bei wiederholtem Klicken, manchmal nicht.

**Comment by jensschnitzler** [comment]
ich habe ein bisschen daran rumgebaut und hoffe das es jetzt besser funktioniert … keine ganz einfache angelegenheit. bitte nach dem nächsten upload noch mal testen :-)

**Comment by silvabaum** [comment]
scheint zu funktionieren (chrome)
