### ISSUE TITLE
Deutsche Antworten auf englischer Seite

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#168]
Unter Inspiration > What inspires you? werden neben einer englischen Antwort auch mehrere deutsche Antworten aufgeführt, obwohl die entsprechenden Interviews die Visibility-Checkbox im Panel für Englisch nicht ausgewählt ist. Allerdings sind in diesen Interview im englischen Panel die entsprechenden Fragen schon in Englisch ausgewählt. Könnte das etwas damit zu tun haben?

![bildschirmfoto 2017-12-21 um 13 13 03](https://user-images.githubusercontent.com/33488569/34255483-2d337f22-e651-11e7-941d-974858c36cf4.png)
 
![bildschirmfoto 2017-12-21 um 13 18 45](https://user-images.githubusercontent.com/33488569/34255542-850f7764-e651-11e7-860c-4ea5d1731f9c.png)

Update:
Kommt auch bei anderen Fragen vor:
![bildschirmfoto 2017-12-21 um 13 20 54](https://user-images.githubusercontent.com/33488569/34255622-d706ada8-e651-11e7-961d-ef423dc002d1.png)

**Comment by jensschnitzler** [comment]
ich hoffe das ist jetzt gefixt, bitte testen und schließen

**Comment by silvabaum** [comment]
check!
