### ISSUE TITLE
"Answers" Interne Links

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#18]
@jensschnitzler, @otcn 

Beim Einfügen von Test-Antworten ist mir aufgefallen, dass ich zwar externe Links, z.B. auf die Website eines Studios einfügen kann, aber keine internen Links. Dazu zwei Anmerkungen.
externe Links werden mit einem schrägen Pfeil hinter dem link ausgezeichnet.
interne Links werden mit einem horizontalen Pfeil vor dem link ausgezeichnet.

Frage:
Kopieren wir diese Pfeile manuell beim Einfügen mit hinein? Dann könnten wir ja auch einfach die jeweilige Adresse unserer eigenen Seite verlinken.
Oder wird das von euch voreingestellt? Dann bräuchten wir im Panel eine zweite Option, interne Links einzufügen.

**Comment by otcn** [comment]
Hey @leasievertsen,

am schmoofsten wäre es, wenn es für interne- und externe Links jeweils eine spezifische Klasse gibt (das haben Jens und ich schon getestet, das klappt) und wir per CSS das jeweilige Zeichen an die Klasse hängen. 

@jensschnitzler Ich würde vorschlagen, dass man das im CSS über Pseudo-Objekte (before, after) macht. Oder kennst du eine bessere Lösung?

**Comment by jensschnitzler** [comment]
Hi @leasievertsen, hi @otcn , genau so machen wir es mit den Pfeilen, um die müsst ihr euch bei der eingabe nicht kümmern.
jana hatte ein praktisches jquery schnippsel geliefert, dass externen links die eine klasse und internen links die andere klasse verpasst.

Wenn ich mich nicht vertue, müsst ihr trotz allem die links als html einfügen, in folgender form:

**Interner link zu einem interview:**
`<a href="../anna-haas">Anna Hass' Interview</a>`

**Interner link zu einem bestimmten abschnitt in einem interview:**
`<a href="../anna-haas#id123">Anna Hass' Antwort</a>`

**externer link:**
`<a href="www.google.de">Hier geht's zu Google</a>`
