### ISSUE TITLE
content/site.txt

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#19]
Hi @otcn , im Ordner content befindet sich eine site.txt, bei der ich nicht weiß, ob sie weg kann oder nicht!? Weißt du noch, ob die obsolet ist?

<img width="1278" alt="bildschirmfoto 2017-11-07 um 22 08 08" src="https://user-images.githubusercontent.com/14975858/32517961-73bfe266-c408-11e7-82ad-506d61067637.png">

**Comment by otcn** [comment]
Hey @jensschnitzler,

Ne, die brauchen wir. Das Plug-In, dass Malte geschrieben hat, damit die fid‘s pro angelegter Frage durchgezählt werden „endet“ auf der site.txt. Deswegen auch der „questioncounter“

Abgesehen davon ist die von Kirby glaube ich auch gernell gefordert. Da würde ich mein Arsch jedoch nicht drauf verwetten.

**Comment by janareddemann** [comment]
Ja, sollte drin bleiben. Da stehen neben dem Counter auch die Metadaten der Seite drin, wie zum Beispiel der Titel, der oben im Browser oder im Verlauf angeziegt wird, oder die Beschreibung, die bei Suchmaschinen angezeigt wird.

**Comment by jensschnitzler** [comment]
sweet, dubbele merci
