### ISSUE TITLE
Interviews/Interview-Unit/Topics

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#20]
@otcn, weißt du, oder Malte, ob es möglich ist, dass wir beim Anlegen von Interview-Units nicht das  Thema angeben müssen? 
Die Fragen sind doch eigentlich eh darunter gespeichert und irgendwo einander zugeordnet, oder? Das würde das Einpflegen erleichtern und auch die Fehlerquelle wegnehmen, dass wir das falsche Thema zur Frage angeben. Da es einige sind, kennen wir die Zuordnungen nicht auswendig und müssen es immer mit der Katalogübersicht abgleichen.

![bildschirmfoto 2017-11-08 um 15 12 30 2](https://user-images.githubusercontent.com/33488569/32553716-f4cb19f4-c497-11e7-8bdf-14315459eb2e.png)

**Comment by otcn** [comment]
Hey @silvabaum,
für das Interview selber ist das nicht relevant. Für das automatische Zusammensetzen (so, wie wir es gebaut haben) der Liste auf der Startseite schon. Da müssen die Fragen ja den Themen zugeordnet werden können.

**Comment by silvabaum** [comment]
Aber die Fragen sind doch eh schon den Themen zugeordnet?

![bildschirmfoto 2017-11-08 um 15 57 35](https://user-images.githubusercontent.com/33488569/32555611-90cf17ba-c49d-11e7-9f85-44fd2912d92f.png)

**Comment by otcn** [comment]
Das stimmt, aber in dem Dropdown werden die einfach nur gelistet (ohne, dass – zumindest ich – zurückverfolgen könnte, wo sie herkommen). Der gedanke war ja, dass man der Vergleichbarkeit halber die Fragen nicht abtippt. Die Fragen könnten im Backend auch einfach nur so gelistet sein, eure Struktur hab ich eigentlich beibehalten, un euch eben das zu vereinfachen. Du musst ja über die Kategorie gehen, um eine neue Frage hinzuzufügen. Das heißt eigentlich müsstest du ja wissen in welcher Kategorie du dich befindest und gar nicht mehr nachschauen. Oder hab ich da an eurem Workflow grundlegend etwas falsch verstanden?

**Comment by silvabaum** [comment]
@otcn > Das stimmt, aber in dem Dropdown werden die einfach nur gelistet (ohne, dass – zumindest ich – zurückverfolgen könnte, wo sie herkommen). Der gedanke war ja, dass man der Vergleichbarkeit halber die Fragen nicht abtippt. Die Fragen könnten im Backend auch einfach nur so gelistet sein, eure Struktur hab ich eigentlich beibehalten, un euch eben das zu vereinfachen. Du musst ja über die Kategorie gehen, um eine neue Frage hinzuzufügen. Das heißt eigentlich müsstest du ja wissen in welcher Kategorie du dich befindest und gar nicht mehr nachschauen. Oder hab ich da an eurem Workflow grundlegend etwas falsch verstanden? <

Ich glaube wir reden aneinander vorbei, ich versuche noch mal mein issue besser zu formulieren:

Wenn ich im Interview eine neue Interview Unit anlege, kann ich die Frage aus einem Dropdown auswählen, das ist sehr gut!
Ich muss aber auch ein Topic auswählen:

![bildschirmfoto 2017-11-08 um 15 12 30 2](https://user-images.githubusercontent.com/33488569/32578672-62f101fa-c4de-11e7-80bf-86b6b94e89f8.png)


Im Bereich "Themen" im Panel lege ich die Fragen **aber auch schon** unter genau einem Topic an:

![bildschirmfoto 2017-11-08 um 15 57 35](https://user-images.githubusercontent.com/33488569/32578063-27d30eee-c4dc-11e7-9734-67f8782cbc24.png)

Meine Frage war, ob durch das Anlegen der Frage (als page eines Themas) die Frage nicht schon dem Thema zugeordnet ist, sodass das Auswählen des Themas beim Anlegen einer neuen Interview Unit überflüssig ist?
Das wäre für uns eine Erleichterung, da wir beim Einpflegen der Interviews ja nicht über die Thema > Frage-Struktur gehen, sondern über das Interview Unit-Panel aus Screenshot 1. 

Außer dass es umständlich ist, sehe ich die Gefahr, dass wir der Frage beim Anlegen des Interviews aus Versehen ein falsches Topic zuweisen, sodass es dann widersprüchliche Zuweisungen gibt (die durch das Anlegen der Frage als page eines bestimmten Themas und unsere falsche im Interview Unit-panel).

**Comment by otcn** [comment]
Hey @silvabaum,
ja, entschuldige – nachdem ich meinen Kommentar gepostet hab, ist mir auch aufgefallen, dass wir aneinander vorbei geredet haben. ich war an einer anderen Stelle. Der erste Teil meiner Antwort stimmt aber dennoch: "Das stimmt, aber in dem Dropdown werden die einfach nur gelistet (ohne, dass – zumindest ich – zurückverfolgen könnte, wo sie herkommen). Der gedanke war ja, dass man der Vergleichbarkeit halber die Fragen nicht abtippt. Die Fragen könnten im Backend auch einfach nur so gelistet sein...". So wie die Seite momentan aufgebaut ist, kommt ihr da leider nicht drum rum. So leid es mir tut :-(

**Comment by jensschnitzler** [comment]
yo guyz, ich schließe das hier mal, oder? sonst könnt ihrs auch wieder öffnen …
