### ISSUE TITLE
Interview Overlay/Question

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#21]
@otcn @jensschnitzler 
Es scheint als würden im Interview Overlay die Fragen (Interview Text Unit -> Question) gerade aus den "Alt-Fragen" gebildet werden. Bei Interviews mit mehreren Personen (Pandan, Grafikladen, Studio Noi) sollen aber natürlich nicht die Alt-Fragen verwendet werden (da meist Sigular-Version der Frage).

![bildschirmfoto 2017-11-08 um 15 47 13](https://user-images.githubusercontent.com/33488569/32555101-2266a3de-c49c-11e7-97ee-8c5f893f8450.png)

**Comment by silvabaum** [comment]
Ah, 'tschuldigung, ist schon berücksichtigt, oder?

**Comment by jensschnitzler** [comment]
Bin mir nicht sicher, ob ich das verstehe … Was war denn der Zweck der Alt-Frage?

**Comment by otcn** [comment]
Hey @silvabaum,
ihr habt in jedem Interview ja die Möglichkeit über eine Checkbox anzugeben, ob es sich um einen, oder um mehrere Interviewpartner handelt. Je nachdem, was ihr da checked wählt Kirby die "normale" oder die alternative Frage aus.

**Comment by silvabaum** [comment]
Ja, @otcn, das habe ich dann danach auch gefunden. War zu schnell mit Issue schreiben. Sorry :)

**Comment by jensschnitzler** [comment]
"Normale Frage" -> ist im Plural formuliert.
"Alt-Frage" -> ist im idR Singular formuliert.
