### ISSUE TITLE
Obsolet? interviews.php, menu.php

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#23]
Hi Tim,

kannst du ausmachen, ob wir folgende Snippets noch brauchen oder es Relikte sind?
Liste von snippets, die so aussehen, als würden wir sie nicht mehr brauchen:

- menu.php
- interviews.php
- coverimage.php
- prevnext.php
- showcase.php
- pagination.php

Weitere obsolete Code-Zeilen vermute ich im `header.php` und `footer.php`. dort habe ich die verdächtigen zeilen auskommentiert und kommentiert.

**Comment by jensschnitzler** [comment]
Weitere obsolete Code-Zeilen vermute ich im `header.php` und `footer.php`. dort habe ich die verdächtigen zeilen auskommentiert und kommentiert.

**Comment by jensschnitzler** [comment]
und `coverimage.php` sieht verdächtig obsolet aus …

**Comment by janareddemann** [comment]
interviews.php wird nicht genutzt und coverimage.php, menu.php, pagination.php, prevnext.php und showcase.php sind Überbleibsel aus dem Kirby StarterKit. Können alle weg ... :)
