### ISSUE TITLE
"templates/interview.php" VS "snippets/interview.php"

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#24]
Hi!

Es gibt zwei Dateien, die so aussehen, als würden sie ein Interview darstellen wollen:

- "templates/interview.php"
In dieser Datei steht schon was von Ajax drin. Diese Datei wird zu Zeit verwendet, um Interviews darzustellen.

- "snippets/interview.php"
In dieser Datei ist der Aufbau schon so, wie ich ihn im Dummy gebaut hatte bzw. wie er von css/js berücksichtigt wird.

Sind die beide notwendig? Falls nein, wo muss der Interview-Code liegen? Da sonst alle Overlays in Ornder "snippets" liegen, wahrscheinlich dort, oder?

**Comment by jensschnitzler** [comment]
Ich habe "templates/interview.php" archiviert und durch das "interview.php" ersetzt, das bisher in den Snippets lag. 
Den PHP/Ajax Code habe ich übertragen und ein paar Zeilen auskommentiert, von denen ich glaube, dass sie evtl überholt sind.

**Comment by janareddemann** [comment]
templates/interview.php wird angesteuert, wenn man direkt auf eine Unterseite geht:
http://dev.notamuse.de/interviews/hannelore-kohl

snippet/interview.php wird von templates/home.php und templates/about.php genutzt, um den Container zu laden, in den bei einem AjaxCall der Inhalt aus der templates/interview.php reingeladen wird.
Da es aber nur `<div class="interview-container overlay hidden"></div>` ist, könnte man sich das Snippet auch sparen und es direkt in die beiden Dateien (home und about) schreiben.
