### ISSUE TITLE
Kirby & PHP being weird: To many P's

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#25]
Hi!

Im interview.php steht folgender PHP/Kirby Code:

<img width="455" alt="bildschirmfoto 2017-11-10 um 17 35 13" src="https://user-images.githubusercontent.com/14975858/32668419-c75e5b82-c63d-11e7-8e12-d727a5458d3b.png">

Und raus kommt dabei das:

![bildschirmfoto 2017-11-10 um 17 34 47](https://user-images.githubusercontent.com/14975858/32668418-c747d5ce-c63d-11e7-9785-b4ed7d2655d4.png)

Gerne hätte ich aber das hier:

`<p class="i-question">Ich bin die Vorfrage. Und ich bin die Frage.</p>`
`<p class="i-answer">Ich bin die Antwort.</p>`

Oder dieses:

`<p class="i-prequestion">Ich bin die Vorfrage.</p>`
`<p class="i-question">Und ich bin die Frage.</p>`
`<p class="i-answer">Ich bin die Antwort.</p>`

**Comment by janareddemann** [comment]
Kirbytext wird irgendwie nicht in `<p>`s gewrapt. Hatte ich auch schon häufiger versucht. :)

Eine einfache Abhilfe ist, dass man den Kirbytext in ein `<div>` steckt, das die gewünschte Klasse hat:

`<div class="i-intro"><?= $interview->introduction()->kirbytext() ?></div>`

Das wrappt problemlos und übers CSS kann man es dann ja beispielsweise als `.i-intro p` ansprechen.

**Comment by jensschnitzler** [comment]
Herrlich

![bildschirmfoto 2017-11-11 um 11 09 06](https://user-images.githubusercontent.com/14975858/32688429-c657d8b0-c6d0-11e7-9135-b574e7a3ab00.png)
