### ISSUE TITLE
Ausgabe von Field Types "url()" und "date()"

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#26]
Wie gebe ich die Field Types "url()" und "date()" richtig aus? In Kombination mit `->html()` oder `->kirbytext()` bekomme ich eine Fehlermeldung :'-(

Das Feld mit "type: url" trägt den Namen "web".

Das Feld mit "type: date" trägt den Namen "date" und sollte das Datum im Format DD.MM.YYYY ausgeben.

**Im php steht es so:**

`<li><?= $interview->web() ?></li>`
`<li><?= $interview->date() ?></li>`

**Raus kommt das hier:**

`https://github.com/otcn/notamuse/wiki/Editor's-Note` 
(ist das richtig? oder kann kirby das direkt als `<a>`-Element ausgeben?)

`1510272000` 
(Im Panel Field habe ich "10.11.2017" eingegeben)

**Comment by janareddemann** [comment]
Das Datum bekommst du so als formatierten String:  

`<?= date('d.m.Y', $interview->date()) ?>`

Hier die Erklärung dazu: http://php.net/manual/de/function.date.php  
Da stehen auch alle anderen Kürzel drin, die verwendet werde können.

**Comment by janareddemann** [comment]
Die URLs würde ich einfach so ausgeben:  

`<a href="<?= $interview->web() ?>"><?= $interview->web() ?></a>`

Das Kirby sie direkt als Link auszugeben, geht meines Wissens nach nicht ...

**Comment by jensschnitzler** [comment]
Wunderbar, dankeschön!
