### ISSUE TITLE
Navigation: Fragen nicht alphabetisch sortiert 

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#27]
Hi!

In der Navigation werden die Fragen noch nicht mit alphabetischer Sortierung ausgegeben.
Das relevante snippet heißt "navigation.php".
Es wird zwar im Code eine Sortierung vorgenommen, aber evtl an der falschen Stelle. Dort steht:

`foreach($pages->find('interviews')->children()->visible() as $interview) {`
`    foreach($interview->interview()->toStructure()->sortBy('frage', 'asc') as $frage) {`

Kann es sein, dass das in bedeutet:

1. Nimm das erste Interview (von allen Interviews die es gibt).
2. Sortiere die Interview-Units (das ist die Kombination von Frage und Antwort, hier: `$interview->interview()` ) dieses Interviews alphabetisch (nach "Frage") und nimm dann davon die erste Interview-Unit.
3. usw.

Es werden also die Fragen nur innerhalb eines Interviews alphabetisch sortiert. Besser wäre dann etwas wie:

1. Nimm das erste Interview.
2. Nimm davon alle Interview-Units und füge sie dem Array "Alle-Interview-Units" hinzu
3. … usw mit allen Interviews
4. Sortiere die Elemente des Arrays "Alle-Interview-Units" alphabetisch.
4. Entferne doppelte Elemente des Arrays "Alle-Interview-Units".

![bildschirmfoto 2017-11-11 um 11 11 34](https://user-images.githubusercontent.com/14975858/32688463-757876c4-c6d1-11e7-9a40-e5b98e690264.png)

**Comment by jensschnitzler** [comment]
wurde es gefixed oder hatte mich vertan? auf jeden fall sind die fragen jetzt alphabetisch und ich close dieses issue

**Comment by otcn** [comment]
Hey @jensschnitzler,
leider ist das noch nicht gefixed. Die Sortierung ist besser als vorher, aber die Buchstaben „S“ und „P“ (beispielsweise) kommen immernoch nach „W“. 

Das ist mal wieder eine Stelle, die komplexer ist, als sie aussieht. Ich hab‘s bisher nicht hinbekommen.
