### ISSUE TITLE
🙈 AJAX

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#28]
Hi!
Leider verwehrt sich mir Ajax leider bisher.

**Die momentane Situation:**

In der Navigation links klicke ich unter _Interviews_ auf _Christiane Funken_ und das Element _interview-container_ öffnet sich von rechts, legt sich über die anderen Inhalte und ist leer :'-( 

Allerdings: Über rechtsklick auf _Christiane Funken_ -> "in neuem Tab öffnen" gelange ich auf die separate Seite "notamuse/interviews/Christiane-Funken". Dort wird das vollständige Interview mit korrekten html-tags usw dargestellt.

 **Die Wunschsituation:**

Der _interview-container_ enthält die Daten, die bisher nur auf der separaten _Interviewseite_ zu finden sind.

---
Welche Dateien haben ihre Finger im Spiel?

- /assets/js/script.js
(enthält den Ajax Code)
- /site/snippets/interview.php
(enthält den _interview-container_)
- /site/templates/interview.php
(enthält die Daten der _Interviewseite_)

Evtl auch noch relevant:

- /assets/js/overlay.js
(enthält den Code zum Öffnen und Schließen der "Overlays", wie dem _interview-container_)
- /site/templates/home.php
(platziert das Snippet "interview.php")

**Comment by janareddemann** [comment]
Hey,

habe gerade einen Ajax-Branch aufgemacht und zwei Commits reingesetzt, weil es geschriben wahrscheinlich zu unübersichtlich geworden wäre.

im Commit d69048c62fc5d39e66f6a41bf9b488f3aed39823 sind Änderungen an der JS. Habs eigentlich nur aufgeräumt und unnötige Überbleibsel entfernt. Bei mir klappte es auch im alten Zustand schon gut ... 
Vielleicht liegt es am Username in der URL?!  ` url: 'http://localhost/~jensschnitzler/' + uid,`
Kannst du die Seite auch einfach über `http://localhost/` erreichen?

Im andern Commit 6791f913d9031f2a24c153158d82c52c64c9bef8 habe ich es nochmal an euren aktuellen Stand angepasst. 
Das ist eigentlich nur dafür da, dass die Seite alles (Header, Menu, Footer etc.) enthält, was sie braucht, wenn sie direkt angesteuert und über einen httprequest ausgeführt wird. 
Wenn die Anfrage über Ajax kommt, wird der Teil dann nicht mit ausgegeben.
Dafür ist das hier da:
```
<?php
if(!kirby()->request()->ajax()) {
    snippet('header');
    ....
}
?>
```

**Comment by jensschnitzler** [comment]
Hi Jana, danke! die Navi funktioniert jetzt schon mal :-)

Die nächste hürde an der ich gescheitert bin sind die links in der topic-liste zu den interviews. und zwar sind das die  interview titel über den antworten:

![bildschirmfoto 2017-11-13 um 18 04 34](https://user-images.githubusercontent.com/14975858/32738428-26a03a78-c89d-11e7-848d-32d1c2b7cec6.png)

Also auf dem Screenshot sollte der Titel ("Johanna Dreyer …") auf das Interview mit "Grafikladen" führen (url unten links im screenshot). stattdessen lädt die ganze seite einfach neu. ich hatte gehofft, dass es reicht im "script.js" in den zeilen, in denen der anchor aus der navigation erwähnt wird, den aus der topic liste hinzuzufügen:

`35 $(document).on('click', '.nav-interview a, a.interviewee-title', function(e) { …`
`45 $(document).on('click', '.nav-interview a, a.interviewee-title', function(e) { …`

Aber so einfach schien es dann leider doch nicht zu sein :-(

Und: bei hover über den interview titel wird rechts das entsprechende foto als vorschau dargestellt. es handelt sich dabei um dasselbe bild, das auch angezeigt wird, wenn das interview-overlay geöffnet ist. noch ist es leider immer das foto des letzten zuvor geöffneten interviews. was ja sinn macht, da das interview von "grafikladen" noch garnicht geladen ist.

ich habe erfolglos versucht in "script.js" zu ergänzen, dass ein interview (bei mouseenter auf dem anchor) in den interviewcontainer geladen wird, ohne dass sich die url ändert.

Noch eine Ajax-bezogene Sache ist, dass sich die url nicht auf notamuse.de zurückändert, wenn ich ein interview wieder schließe.

ich werde mir nächste woche auch mal genauer history.js anschauen, vlt erklärt sich mir dann etwas besser, wie das alles umzusetzen ist.

**Comment by janareddemann** [comment]
So, ich machs mal step by step, um nicht durcheinander zu kommen.

4e2746e666c27485c3140d48d2ee280bee796382
364d1c23bb0c2f67e0ab5768c80f627a5e49e6bc
Ich habe die overlay.js und script.js jetzt in einer Datei zusammengefasst, weil sie sich ein bisschen in die Quere gekommen sind. Also nciht wundern, dass bei der overlay.js jetzt alles auskommentiert ist.

Ich habe überhaupt keine Ahnung, warum das $(document).on('click', '.class', function(e){}); nicht geklappt hat. Das ist eigentlich immer der sichere Weg. In dem Fall gehts aber nur mit $('.class').on('click', function(e){});. Jetzt gehen aber beide Wege, also über Navi und über Interview.

Die URL ändert sich jetzt auch wieder zurück, wenn man ein Interview verlässt.

**Comment by janareddemann** [comment]
Die Vorschau klappt noch nicht. Davon habe ich aber auch eben das erste Mal was gehört/gesehen. In der PDF war das irgendwie nicht mit drin. 
Das über Ajax zu laden, ist glaube ich nicht so cool. Würde da mal einen ganz andern Weg ausprobieren, daher hatte ich schon mal den ersten Teil hier reingesetzt ...

**Comment by janareddemann** [comment]
So preview ist auch drin.

Ich habe in der home.php noch einen neuen Container für das Vorschaubild hinzugefügt:  
1f7663b830ef742addcb595c878b770e7280d437
Jede '.interviewee-title' hat jetzt die image source des ersten Bilds als Attribut bekommen:  
7df96ae4f249fdff04051db3eca3307f2c032c6e
Wenn man hovert, bekommt der Vorschaucontainer die image source:  
4e947d0ab76ee6bb917417e2b9af0d51a9626484
Und ein wenig CSS:  
4e947d0ab76ee6bb917417e2b9af0d51a9626484  

Ich weiß nicht, ob das genau das ist, was ihr haben wolltet, aber ich glaube das grobe steht damit und den Rest könnt ihr daran ändern?! Also genaue Positionierung, Timeout statt Mouseenter/Mouseleave etc.

**Comment by janareddemann** [comment]
Ups, soll das Vorschaubild auch dann kommen, wenn man in der topic-liste zu den Interviews hovert? Dann muss da noch die imgsrc dran. Wenn nicht, muss das '.nav-interview a' aus dem Mouseenter/Mouseleave raus ...

**Comment by janareddemann** [comment]
Commitchaos. Sorry!  
Habe gerade erst gesehen, dass die About Seite noch nicht direkt ansteuerbar war. Ist jetzt ein bisschen hacky, aber was solls. :/  

27586633bac5aa382323b52ccaafd90302137327
7a48c293af6f68ff7fced3225082cdb394aed8bc

**Comment by jensschnitzler** [comment]
dankeschön :-) jetzt läuft es wunderbar

**Comment by janareddemann** [comment]
Cool. :)

Sag mal, du hast jetzt wieder Defaults fürs Overlay reingesetzt. Sind die notwendig?
Hatte es eigentlich extra rausgenommen, damit man das Intro nicht bekommt, wenn man eine Seite direkt ansteuert ... 
http://dev.notamuse.de/interviews/hannelore-kohl, http://dev.notamuse.de/about etc.

**Comment by janareddemann** [comment]
Hmm, doch noch nicht fertig. Ich habe gerade erst die Spezialfargen in der Navi entdeckt, die direkt das Interview öffnen sollen. (Finde ich auch als Nutzer ziemlich schwer zu verstehen, warum da eine andere Logik greift ...)
Aber die müssen dann auch übers Ajax abgefangen werden. Wenn jens-scripts.js und script.js zusammengeführt werden, gehts hierüber: 

  ```
  $('.nav-question a').click(function(e){
      var anchor = $( this );
      if (anchor.attr('href').indexOf('http') == -1){
        topicLink(anchor);
      }
      else{
        push(anchor.attr('href').split('#')[0])
        e.preventDefault();
      }
    });
```

**Comment by jensschnitzler** [comment]
hab die defaults auch wieder auskommentiert. hatte erst gedacht, du hättest beim kopieren übersehen, aber dann ist mir auch aufgefallen, dass das einen haken hat. ich versuche mal die js's zusammenzuführen und deinen code einzubauen :-)
