### ISSUE TITLE
Interview, Navigation Title

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#29]
Hallo!

In der Navigation "Interview" wird noch nicht der "Navigation Title" ausgegeben, den man im Panel angeben kann (Screenshot 1) sondern der "Interview Title" (siehe Screenshot 2). Es sollte der Navigation Title sein.

<img width="1127" alt="bildschirmfoto 2017-11-11 um 19 29 07" src="https://user-images.githubusercontent.com/33488569/32692393-9c6f75d4-c717-11e7-9f60-8e053886777f.png">

<img width="731" alt="bildschirmfoto 2017-11-11 um 19 28 12" src="https://user-images.githubusercontent.com/33488569/32692392-9c563cd6-c717-11e7-9383-2f58319d09ee.png">

**Comment by jensschnitzler** [comment]
Jetzt sollte es so sein:
Wenn das Feld "Navigation Title" nicht leer ist, wird es ausgegeben.
Ansonsten wird der Inhalt des Feld "Interview Title" ausgegeben. 


`                <?php if( !$interview->titlenav()->empty() ): ?>`
`                  <?php echo $interview->titlenav() ?>`
`                <?php else: ?>`
`                  <?php echo $interview->title() ?>`
`                <?php endif ?>`

**Comment by silvabaum** [comment]
yes, works!
