### ISSUE TITLE
Intro-Overlay interne Links

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#30]
Kleine Erinnerung:

Die Links auf dem Intro-Overlay "Alle Antworten zu dieser Frage" und "Alle Themen im Überlick" funktionieren noch nicht.

**Comment by jensschnitzler** [comment]
should work now

**Comment by silvabaum** [comment]
Ja, aber die Frage öffnet unten auf der Seite und hat einen blauen Rahmen um sich.

**Comment by silvabaum** [comment]
<img width="1164" alt="bildschirmfoto 2017-11-13 um 19 06 05" src="https://user-images.githubusercontent.com/33488569/32741225-be89d6a2-c8a5-11e7-99db-bd5cfa12a29e.png">

so einen

**Comment by janareddemann** [comment]
*:focus {
    outline: 0;
}

**Comment by jensschnitzler** [comment]
fixed

**Comment by silvabaum** [comment]
"Alle Antworten zu dieser Frage" funktioniert wieder nicht, hängt vielleicht mit Issue #90 zusammen?

**Comment by jensschnitzler** [comment]
@silvabaum bitte issues assignen und labeln, sonst übersehe ich die :-)

**Comment by silvabaum** [comment]
"Alle Antworten zu dieser Frage" funktioniert, "Alle Themen im Überblick" nicht

**Comment by jensschnitzler** [comment]
AALLSSOO :-) es funktioniert jetzt (ab dem nächsten upload) so halb:

- von einer  _regulären fragen_ im  _intro_ komme ich jetzt zu der dazugehörigen frage in der _topics-liste_
- von einer _speziellen fragen_ im _intro_ komme ich **noch nicht** zum dazugehörigen _interview_
- die topic-liste sollte jetzt so scrollen, dass die ziel-frage gut im sichtbaren bereich liegt, da ist aber bestimmt noch ein bisschen feintuning notwendig

**Comment by silvabaum** [comment]
Ja, genauso ist es! (in Chrome und in firefox)

**Comment by janareddemann** [comment]
```
  // INTRO: click link to open related answer
  $('.js-intro-answer').click(function(event){
    event.preventDefault(); // prevent the link from following the URL
    var anchor = $(this).attr('href');
    closeSeparator();
    push(anchor);
  });
```

**Comment by jensschnitzler** [comment]
👍  ist eingebaut und funktioniert jetzt bei mir im localhost. nach dem nächsten upload bitte teste und ggf issue schließen, danke
