### ISSUE TITLE
Special Question/ Topic: Spezifisch

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#31]
Hallo, hier noch einen nervige Anfrage zum Panel:

Wenn ich es richtig verstanden habe, funktionieren die spezifischen Fragen gerade so: Unter Themen -> Spezifisch legt man die Frage an, genauso wie man die Katalogfragen anlegt (Screenshot 1). Wenn ich dann im Interview einen spezifische Frage eingeben möchte, setze ich den Haken bei der Checkbox "Special Question" und wähle die Frage dann aus dem Dropdown "Question Catalogue" aus. 

<img width="1280" alt="bildschirmfoto 2017-11-11 um 19 46 22" src="https://user-images.githubusercontent.com/33488569/32692552-11d0254c-c71a-11e7-8f16-51a03b4be14a.png">

<img width="1280" alt="bildschirmfoto 2017-11-11 um 19 44 52" src="https://user-images.githubusercontent.com/33488569/32692553-1385d512-c71a-11e7-9265-63555d72dad9.png">

Meine Frage: Wäre es möglich, dass man die Frage direkt in ein Textfeld eingeben kann, wenn man die Checkbox "Special Question" anwählt? 
Da die spezifischen Fragen alle nur einmal vorkommen, ist dieser aktuelle, zweischrittige Weg (erst woanders eingeben und dann im Dropdown auswählen) ein kleiner Umweg. Außerdem wird das Dropdown so sehr lang, da es bestimmt ca 50 spezifische Fragen sind, die noch dazu kämen.

**Comment by jensschnitzler** [comment]
@silvabaum close?
