### ISSUE TITLE
Main Layer/Topics: verkürzte Interviewantworten

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#32]
@jensschnitzler 

Bitte die vollständigen Antworten anzeigen!

<img width="1046" alt="bildschirmfoto 2017-11-11 um 20 25 43" src="https://user-images.githubusercontent.com/33488569/32692791-da1eca86-c71e-11e7-8ec0-7efe51abdbb2.png">

**Comment by jensschnitzler** [comment]
fixed
