### ISSUE TITLE
Main Layer/Topics: zu viele Themen oO

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#33]
@jensschnitzler, auf dev.notamuse.de werden noch zwei Themen angezeigt, die es im Panel nicht gibt und auch nicht geben soll: Arbeitsprozess und Arbeitssituation. Bitte löschen!

**Comment by jensschnitzler** [comment]
sind sie jetzt weg?

**Comment by silvabaum** [comment]
ja
