### ISSUE TITLE
Border unter Topic bleibt beim Schließen sichtbar

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#36]
@jensschnitzler 
<img width="1045" alt="bildschirmfoto 2017-11-11 um 21 36 48" src="https://user-images.githubusercontent.com/33488569/32693274-755e5e90-c728-11e7-9bc7-9a864683cf0a.png">

**Comment by jensschnitzler** [comment]
den fehler kann ich gerade nicht reproduzieren. sollte das noch mal auffallen, bitte hier kommentieren.

**Comment by otcn** [comment]
Das passiert scheinbar nicht, wenn man ganz "normal" durch die Topics navigiert. Ich bekomm den Fehler reproduziert, wenn ich:

1. Mehrere Topics öffne
2. Dann in der Navigation die Fragen öffne
3. Dann auf eine Frage klicke

Wenn ich das Topic, dass ich über das Klicken der Frage in der Nav geöffnet habe dann manuell schließen will, ist der Unterstrich weiterhin zu sehen

![bildschirmfoto 2017-11-12 um 22 50 25](https://user-images.githubusercontent.com/24541531/32703873-8fb563ea-c7fc-11e7-8289-c40d0a0d28af.png)

**Comment by otcn** [comment]
Beim zweiten Versuch war der erste Schritt meiner "Aktionsliste" nicht mehr nötig. Das problem entsteht also, wenn man über die Nav in ein Topic navigiert.

**Comment by janareddemann** [comment]
Beim Klick über die Navi bekommt .topic-item keine .active Klasse, daher funktioniert der toggle danach genau umgekehrt. Also einfach:

```
function topicLink(anchor) {
  ...
  topicItem.addClass('active');
};
```
Und vielleicht noch das, um die Border in der Navi zu verstecken, wenn man auf ein .topic-item geklickt hat?!

```
$('.parent').children().click(function(){
  ...
  $('.nav-switch').removeClass('active'); 
})
```

(Weiß teilweise nicht, wie es genau geplant ist und rate ein bisschen, was der gewünschte Zustand sein könnte ...)

**Comment by jensschnitzler** [comment]
danke @zweipi  ! 

habe den code eingebaut und kann den fehler jetzt auch nicht wieder auslösen.

@leasievertsen @silvabaum @claudiascheer 

nach dem nächsten upload bitte testen und ggf issue schließen

**Comment by silvabaum** [comment]
habe den Fehler nicht gefunden
