### ISSUE TITLE
Hoverstate der Topics hinterlässt Artefakte in den Unterlängen (Safari)

### ISSUE THREAD

**Issue by otcn** [otcn/notamuse#39]
Hey! Sollte keiner von euch in Safari arbeiten und es noch nicht bemerkt haben. 

![bildschirmfoto 2017-11-13 um 00 41 44](https://user-images.githubusercontent.com/24541531/32715894-4f3317ce-c854-11e7-836a-9929188097e6.png)
![bildschirmfoto 2017-11-13 um 00 42 55](https://user-images.githubusercontent.com/24541531/32715895-4f5cbea8-c854-11e7-9d36-a40eac831fa3.png)

**Comment by janareddemann** [comment]
Safari is the new Internet Explorer!

```
.topic-title a{
  ...
  padding-bottom: 2px;
}
```

![screen shot 2017-11-14 at 19 46 35](https://user-images.githubusercontent.com/9757393/32799356-c42c7c2c-c977-11e7-99d6-94c7d71b9289.png) 

vs. 

![screen shot 2017-11-14 at 19 46 20](https://user-images.githubusercontent.com/9757393/32799355-c3d3a5b6-c977-11e7-80c9-e8238bef84a3.png)

**Comment by jensschnitzler** [comment]
obrigado! css ist drinn, bitte bei gelegenheit noch mal testen.

**Comment by silvabaum** [comment]
geht!
