### ISSUE TITLE
Interviewantwort mit mehreren Absätzen

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#40]
Hallo! 
Bei Interviewantworten, in denen sich ein Absatz befindet, werden die Absätze einzeln unter der Frage ausgegeben, jeweils mit dem Interview Title überschrieben:
<img width="1194" alt="bildschirmfoto 2017-11-14 um 16 46 52" src="https://user-images.githubusercontent.com/33488569/32789186-7bd67d2c-c95b-11e7-9134-d67eb832f169.png">

Die drei Absätze von Laure Boer sind natürlich eigentlich eine Antwort und sollten auch zusammenhängend dargestellt werden.

**Comment by jensschnitzler** [comment]
fixed
