### ISSUE TITLE
Hover Namen und Links (CSS)

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#41]
Beim Hover über Links sollte der Link unterstrichen werden.
Das Bild beim Hover auf Namen (Interview Title) erscheint, bleibt aber zu lange stehen. Diese Verzögerung bitte reduzieren, sonst verdeckt es zu lange den Text, den man lesen will.

**Comment by silvabaum** [comment]
Links auf dem Interview Overlay werden gerade extended, sollten aber wie auf dem Main Layer Pfeil und Unterstreichung bekommen.

**Comment by jensschnitzler** [comment]
**Verzögerung der Sichtbarkeit beim Preview Bild** ist jetzt ganz raus, wenn ihr doch wieder eine gewisse Toleranz haben wollt, gebt bescheid.

**Links auf dem Interview Overlay** werden jetzt richtig ausgezeichnet.
