### ISSUE TITLE
mobile/responsive Ansicht

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#43]
mobile/repsonsive Ansicht: Wie sieht die Seite auf dem Smartphone aus? Auch in ganz groß sieht sie Seite grauenhaft aus. Am besten skalierbare Größen nach Browserfeldgröße?
<img width="961" alt="bildschirmfoto 2017-11-20 um 17 24 09" src="https://user-images.githubusercontent.com/33448884/33084608-ad4f2872-cee2-11e7-8cc3-446726831406.png">

**Comment by jensschnitzler** [comment]
hi, das wäre erstmal ein design issue. technisch sieht es so aus, dass sich die elemente sowohl relativ zur bildschirmgröße verhalten können, als auch, dass wir an bestimmten breakpoints das layout verändern, wie zb das menü an eine andere stelle schieben oder hinter einem button verstecken …

**Comment by jensschnitzler** [comment]
ich habe diesem issue zur priorisierung das label "nice to have" zugewiesen, da ich bisher das so verstanden habe, dass das etwas wäre, was nicht um jeden preis bis zum 8.12. gelöst sein muss.

**Comment by claudiascheer** [comment]
@jensschnitzler Ich könnte mir vorstellen dass schon viele übers Smartphone auf die Seite gehen (grade wegen unserer tollen Instagram-Posts ^^) – meinst du könnte es klappen dass sie auf dem Smartphone funktioniert bis zum 8.12.?

**Comment by jensschnitzler** [comment]
@claudiascheer du hast recht, das wäre auf jeden fall besser :-) bis wann könntet ihr denn den responsive entwurf fertig machen?

**Comment by claudiascheer** [comment]
@jensschnitzler falls du es noch nicht gesehen hast, es gibt dazu ein extra issue, in dem liegt auch der entwurf als pdf :)

**Comment by jensschnitzler** [comment]
@claudiascheer ist der von euch schon zur umsetzung freigegeben? dann assigne mich gerne in dem issue :-)

**Comment by silvabaum** [comment]
@jensschnitzler wir haben da noch ein paar kleine Änderungen dran, wie Schriftgrößen anzupassen, genaueres steht in issue #76. Mit der Skalierung am desktop setze ich mich jetzt auseinander, bis zu einem bestimmten Breakpoint soll der Inhalt aber erstmal stufenlos skalieren.

**Comment by leasievertsen** [comment]
Das funktioniert am 15" Macbook schon recht gut finde ich! ich versuche es am Donnerstag mal auf einem großen IMac zu testen.

**Comment by silvabaum** [comment]
@jensschnitzler, folgende Anpassungen könnten wir noch machen:

```
.answer-item {
    margin: 33px 0px 0px 0px;
    width: 65vw;
    max-width: 700px;
    min-width: 500px;
```

Die Topics nicht umbrechen lassen

**Comment by jensschnitzler** [comment]
@silvabaum check

**Comment by silvabaum** [comment]
@jensschnitzler, sieht schon gut aus, schaue mir später noch mal die min-width an,  die könnte vllt. noch größer.
Die Tonics umbrechen noch, können wir das wieder rausnehmen? Finde die Stelle im Code leider nicht.

**Comment by silvabaum** [comment]
@jensschnitzler, bitte noch die width auf 60vw

```
.answer-item {
    margin: 33px 0px 0px 0px;
    width: 60vw;
```

**Comment by jensschnitzler** [comment]
👍 die topics sollten jetzt nicht mehr umbrechen :-)

**Comment by jensschnitzler** [comment]
könntet ihr für neue korrekturen , egal ob sie nun mobile oder desktop betreffen, jeweils ein neues issue anlegen und mich da assignen? ihr könnt dem ja dann, wenn ihr das für sinnvoll haltet, ggf das label "mobile" geben. sonst muss ich immer so viel lesen :-P merci

**Comment by silvabaum** [comment]
check!
