### ISSUE TITLE
externe Links

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#44]
externe Links: führen von der Seite weg, sollte nicht lieber ein neues Tab aufgehen? target="_blank"

**Comment by jensschnitzler** [comment]
auf jeden fall :-)

**Comment by jensschnitzler** [comment]
siehe issue #45

**Comment by jensschnitzler** [comment]
should be _fixed_. test and close plz

**Comment by silvabaum** [comment]
fixed
