### ISSUE TITLE
Formatierung externe Links

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#45]
Formatierung externe Links: noch keine Pfeile bei externen Links

**Comment by jensschnitzler** [comment]
dachte, dass hätte ich schon gefixed. wo wäre so ein falscher externer link?

**Comment by jensschnitzler** [comment]
Der Mirko ist schon mit Pfeil versehen und öffnet in neuem Tab.

<img width="1276" alt="bildschirmfoto 2017-11-21 um 19 29 56" src="https://user-images.githubusercontent.com/14975858/33089906-690a1c48-cef2-11e7-86d2-4e9a12480fe2.png">
