### ISSUE TITLE
Intro Overlay: Zeilenabstände und Positionierung

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#46]
Intro Overlay: Zeilenabstände und Positionierung der Elemente unter dem Zitat stimmen noch nicht mit dem Entwurf überein.

**Comment by jensschnitzler** [comment]
wie verhält sich denn die intro navigation (also der block mit "Frage XY, Alle Antworten zu dieser Frage, Alle Themen im Überblick"), wenn das zitat vertikal mehr raum einnimmt, so dass die die beiden elemente sich überlappen würden?

**Comment by silvabaum** [comment]
Eigentlich dachte ich hätten wir die Zitate so ausgewählt, dass das nicht passiert. Wir haben auf jeden Fall einige geprüft. Das würden wir noch mal mit allen machen, sodass das nicht passiert.
Die Position der Frage und Links ist dennoch noch nicht richtig, die sollten ja unten auf der Seite stehen. Der Overlay sollte auch eigentlich nicht scrollbar sein, obwohl das ja wahrscheinlich quatsch ist, z.B. wenn jemand ein sehr flaches Browserfenster hat, oder?

**Comment by jensschnitzler** [comment]
@silvabaum vlt haben wir ein missverständnis, aber bei eben diesen flachen browserfenstern kann doch gar nicht ausgeschlossen werden, dass sich zitat und navigation berühren?

**Comment by silvabaum** [comment]
@jensschnitzler Ja, das ist mir dann beim schreiben auch bewusst geworden. Wie hatten darauf geachtet, dass die Zitate  bei einem 1440 x 800 (oder so, 15 zoll macbook) Fenster nicht bis nach unten reichen. Wenn das Fenster kleiner wird, soll der Inhalt wahrscheinlich skalieren (Was meint ihr @leasievertsen @claudiascheer?). Wenn das Fenster in der Höhe noch kleiner wird, kann es natürlich passieren, dass die sich überlagern. Dann, würde ich sagen, muss das Intro-Overlay ja doch scrollbar werden. Was meinen @leasievertsen und @claudiascheer?

**Comment by silvabaum** [comment]
@jensschnitzler: auch wenn wir nicht ausschließen können, dass sich etwas berührt, könntest du die Links schon mal unten an der Seite anordnen? Dann kann man sich vielleicht besser vorstellen wie es sich alternativ verhalten könnte.

**Comment by leasievertsen** [comment]
Ich würde scrollbar jetzt auch für die beste option halten.

**Comment by claudiascheer** [comment]
Ihr meint, wenn das Fenster kleiner gemacht wird, skaliert sich der Inhalt mit bis zu Punkt X und danach wird es scrollbar oder? Das finde ich auch gut!

**Comment by silvabaum** [comment]
Ich war heute kurz dabei als Christoph und Jens sich den notamuse-Code angeguckt haben und Christoph hat das mit dem Inhalt-skalieren gezeigt. Das sah so aus als würde es erst mal wieder ziemlich viel durcheinander werfen und ich bin auch nicht sicher ob ich es besser finde als das was Jens bisher gemacht hatte (also dass sich die Abstände verringern, die Spalten schmaler werden, bis es ins mobile geht). Daher würde ich vorschlagen, es erst mal zu lassen wie es ist (ohne skalierung) und wenn alles funktioniert nochmal drüber nachzudenken, was wir am besten finden. (bis zum 8. ist es soweit ich es verstanden habe ohnehin unrealistisch, weil es noch so viel wichtigeres zu tun gibt). Wär das für euch ok, @leasievertsen, @claudiascheer ?

Für das Intro würde ich vorschlagen, dass wir versuchen, die super langen Zitate noch etwas zu kürzen, einen Mindestabstand zwischen Autorin und Frage definieren und dass es, wenn der erreicht ist, scrollt.

![bildschirmfoto 2017-11-29 um 17 03 58](https://user-images.githubusercontent.com/33488569/33385078-0a8689b8-d528-11e7-9d7b-fe19394fef8a.png)

**Comment by claudiascheer** [comment]
ja, ich finde das klingt nach einem guten Plan!

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen por favor.

**Comment by silvabaum** [comment]
nice! 

kleine Anpassung: padding-bottom von .intro.nav.stricky sollte 33px (statt 1rem)

![bildschirmfoto 2017-11-29 um 22 27 24](https://user-images.githubusercontent.com/33488569/33400018-d418ea24-d554-11e7-9e96-8eb7d8d93e0b.png)

Dazu bitte folgendes ändern:
```
.nav > ul > li.nav-spacer {
    margin-top: -278px;
```

**Comment by leasievertsen** [comment]
Ja! Ich habe da keine Idee wie aufwendig weder das eine noch das andere sind, deswegen bin ich auf jeden Fall für die Lösung, die erstmal funktioniert!!

**Comment by silvabaum** [comment]
funktioniert!
