### ISSUE TITLE
Main Layer: Öffnungs/Schließzeichen

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#47]
Main Layer und auch andere Bereiche: Öffnungs/Schließzeichen sind oft noch verkehrtherum (x beim öffnen, + beim schließen)

![bildschirmfoto 2017-11-20 um 16 36 57](https://user-images.githubusercontent.com/33448884/33085318-adb4d95e-cee4-11e7-8bed-335d2195fefd.png)

**Comment by jensschnitzler** [comment]
sollte jetzt gefixt sein. gerne testen, sobald ich den neuesten stand hochgeladen habe.

**Comment by silvabaum** [comment]
fixed
