### ISSUE TITLE
Main Layer/Topics/Questions

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#48]
Topics: zu lange Fragen laufen noch unter dem Banner durch und werden nicht mehrzeilig. 
Es muss so umbrechen, dass das +/x nicht von der Schrift überdeckt wird. Das unterste Bild zeigt wie es im Entwurf gedacht ist.

![bildschirmfoto 2017-11-20 um 16 50 40](https://user-images.githubusercontent.com/33448884/33084916-73325c80-cee3-11e7-918d-19d4b59b6478.png)
 
![bildschirmfoto 2017-11-20 um 16 55 02](https://user-images.githubusercontent.com/33448884/33085053-d7a0be1e-cee3-11e7-91fc-4cb188071fc1.png)

![Uploading Bildschirmfoto 2017-11-20 um 16.54.53.png…]()

**Comment by jensschnitzler** [comment]
@leasievertsen der screenshot scheint nicht fertig hochgeladen zu sein … aber ich glaub ich kanns mir auch so vorstellen :-)

**Comment by jensschnitzler** [comment]
notiz an mich selbst:
`.question-title {white-space: normal;}`
`.question.title a:first-child {max-width: 55vw; display: block;}`
bei .active ggf. max-width vergrößern

**Comment by jensschnitzler** [comment]
sollte jetzt gefixt sein und funktionieren, sobald ich später die aktuellste version auf dev.notamuse geladen habe. @leasievertsen könntest du das dann noch mal testen und ggf. das issue schließen?

**Comment by leasievertsen** [comment]
@jensschnitzler geht leider bei mir noch nicht im chrome..

**Comment by jensschnitzler** [comment]
@leasievertsen hier funktionierts gerade … leere mal deinen cache und versuch es noch mal :-)

**Comment by silvabaum** [comment]
@jensschnitzler schon besser, aber bei manchen Fragen noch etwas knapp (siehe screenshot), max-width vllt noch etwas kleiner

![bildschirmfoto 2017-11-24 um 15 40 17](https://user-images.githubusercontent.com/33488569/33214919-098ebdd0-d12e-11e7-8c30-3569626f00e5.png)

**Comment by jensschnitzler** [comment]
close?
