### ISSUE TITLE
Main Layer/Topics/Questions: Zeilenabstände

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#50]
Main Layer/Topics/Questions: Zeilenabstände sind zu groß.

**Comment by jensschnitzler** [comment]
ist bei mir genau wie in der vorlage:

```
    font-size: 30px;
    line-height: 33px;
```

**Comment by silvabaum** [comment]
@jensschnitzler Zeilenabstände sind ok, aber Abstände zwischen Questions zu groß

**Comment by jensschnitzler** [comment]
@silvabaum close?
