### ISSUE TITLE
Main Layer/Topics/QuestionsAnswers: Zeilenlänge

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#51]
Main Layer/Topics/QuestionsAnswers: Zeilen zu lang, sollen nicht bis zum rechten Rand gehen

**Comment by jensschnitzler** [comment]
<img width="1280" alt="bildschirmfoto 2017-11-21 um 19 21 41" src="https://user-images.githubusercontent.com/14975858/33089554-3b1988a6-cef1-11e7-8da0-6ccff3ea9f78.png">

**Comment by jensschnitzler** [comment]
fixed
