### ISSUE TITLE
Auszeichnung Namenskürzel

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#52]
Topics/Questions/Answers: Auszeichnung der Kürzel z.B. AH “extended”

**Comment by jensschnitzler** [comment]
als erinnerung an mich selbst: https://codepen.io/JensSchnitzler/pen/wPqBvQ

**Comment by jensschnitzler** [comment]
es funktioniert fast, der schlüssel zum erfolg hat mit issue #74 zu tun …

**Comment by jensschnitzler** [comment]
_fixed_
