### ISSUE TITLE
Navigation: Positionen, Abstände

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#53]
Navigation: Themen sitzt zu weit oben
Navigation: Wenn “Interviews” ausgefahren wird, ist der Abstand zwischen dem Bereich “Interview” und der “Topicliste" zu eng. (Linie zu eng an dem Topics-Bereich)
 
<img width="854" alt="bildschirmfoto 2017-11-19 um 12 19 52" src="https://user-images.githubusercontent.com/33448884/33085234-6ae4cb0c-cee4-11e7-8c93-d3de525934b5.png">
aber auch Abstand nach unten noch zu klein)

**Comment by jensschnitzler** [comment]
ist der aktuellste entwurf "171002_Web_NEU.indd", der in der dropbox liegt?

**Comment by leasievertsen** [comment]
Ja genau, das ist er.

**Comment by jensschnitzler** [comment]
_fixed_ aber noch nicht _online_
