### ISSUE TITLE
Navigation: Öffnungs-/Schließelemente

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#54]
Navigation: Bei Interviews und Fragen: Kreuz verschwindet nicht sondern wird wieder zum Plus

![bildschirmfoto 2017-11-20 um 16 57 54](https://user-images.githubusercontent.com/33448884/33102632-fb8216cc-cf1d-11e7-9a6c-b6d9646c6102.png)

**Comment by jensschnitzler** [comment]
der screenshot scheint noch nicht fertig hochgeladen gewesen zu sein. bei technischen issues auch immer gerne den verwendeten browser vermerken, das kann bei der fehlerfindung nützlich sein.

**Comment by jensschnitzler** [comment]
sollte gefixt sein
