### ISSUE TITLE
Navigation: Von Spezialfragen zu Intro

### ISSUE THREAD

**Issue by leasievertsen** [otcn/notamuse#55]
Navigation: Bei Spezialfragen komme ich noch auf “Intro Overlay” und nicht auf die korrekte “Interview Overlay”

**Comment by jensschnitzler** [comment]
In Firefox funktionierts. in welchem browser hast du gestestet, @leasievertsen? und warst du im inkognito/privaten modus?

<img width="1280" alt="bildschirmfoto 2017-11-21 um 19 40 11" src="https://user-images.githubusercontent.com/14975858/33090310-d11b0904-cef3-11e7-8ee3-1d6b1326d3f6.png">

**Comment by jensschnitzler** [comment]
ah nein, hatte aus der navigation ein _interview_ mit spezialfragen ausgewählt. nicht direkt eine spezialfrage unter _fragen_ … dann tritt auch hier der fehler auf, werde ich mir anschauen

**Comment by janareddemann** [comment]
In dem letzten Kommentar in Issue #28 steht da der Code für drin. Hatte ich erst zu spät entdeckt ...

**Comment by jensschnitzler** [comment]
danke, schaue ich mir an!

**Comment by jensschnitzler** [comment]
hi @zweipi ,
folgendes hatte ich im script.js eingefügt, trotzdem lädt die ganze seite neu und ich gelange zum intro, wenn ich in der navigation unter "fragen" auf eine spezialfrage klicke:

```
 /* click on a nav-question to EITHER open scroll to the related answer (under the main topics) OR (in case of a "special question") open the related interview overlay and scroll to the related answer: */
    
$('.nav-question a').click(function(e){
    var anchor = $( this );
    if (anchor.attr('href').indexOf('http') == -1){
        topicLink(anchor);
    }
    else{
        push(anchor.attr('href').split('#')[0])
        e.preventDefault();
    }
});
```

**Comment by janareddemann** [comment]
Du hast in der Javascript Datei 4 verscheidene document.ready Funktionen.  

Die `topicLink(`){} Funktion ist in einer anderen document.ready Funktion als das `$('.nav-question a').click(function(e){})`, die versucht, die erste aufzurufen und daher nicht erreichbar ist.

Nimm mal alle bis auf eine document.ready Funktion, die alles umschließt, raus, dann klappt es schonmal.

**Comment by jensschnitzler** [comment]
👍 ich glaube ich habe es gefixt. checkt es nach dem nächsten update mal aus und testet, schließt, etc, merci

**Comment by leasievertsen** [comment]
Die Spezialfragen öffnen das korrekte interview, aber oben in der Einleitung und nicht an der entsprechenden Stelle des Interviews. (Da könnte man auch erstmal so mit leben finde ich, falls das nicht zu fixen ist)

**Comment by silvabaum** [comment]
Zu meiner These aus #108: der Stand ist der gleiche: man kommt zum richtigen Interview, aber nicht zur bestimmten Frage (Chrome)

**Comment by claudiascheer** [comment]
Same here (Firefox)

**Comment by claudiascheer** [comment]
Bei mir funktioniert es jetzt super!

**Comment by silvabaum** [comment]
check!
