### ISSUE TITLE
Sprache: englische Interviews in deutscher Maske

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#57]
Wie gehen wir mit den englischen Interviews bzw. den englischen Katalogfragen in der deutschen Maske um?  > passt dann in der Ausgabe nicht zusammen (zB. Vorsatz und Antwort auf englisch, Frage auf deutsch) oder lieber englische Spezialfragen anlegen?

**Comment by leasievertsen** [comment]
jana rät uns auf jeden fall die englischen fragen, die im katalog sind und da auftauchen, rauszunehmen.  eventuell könnte sie das noch fixen. aber jens soll das erstmal nicht machen, sonder wichtigeres. wir können jetzt entscheiden ob die interviews noch nur als spezialfragen drin bleiben oder ob wir sie ganz rausnehmen.

**Comment by claudiascheer** [comment]
ich fände sie als spezialfragen nach wie vor gut!

**Comment by silvabaum** [comment]
ich würde sie auch erst mal wieder rausnehmen, können sie einfach wieder auf invisible stellen

**Comment by claudiascheer** [comment]
![bildschirmfoto 2017-11-28 um 14 05 04](https://user-images.githubusercontent.com/33512565/33321225-33571d32-d445-11e7-8d15-9447231394f4.png)

die englischen Interviews in der deutschen Maske müssen wir noch rausnehmen

**Comment by silvabaum** [comment]
Habe die englischen Interviews auf invisible gestellt
