### ISSUE TITLE
Sprache generell: englisch

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#58]
Es gibt nicht alle Interviews auf deutsch und es gibt nicht alle Interviews auf englisch.. Oo Wir haben in der Gestaltung den Deutsch/Englisch Button, wie gehen wir damit um?

**Comment by leasievertsen** [comment]
Jana rät uns: 2. die englischen fragen erstmal rauszunehmen. eventuell könnte sie das noch fixen. aber jens soll das erstmal nicht machen und sich auf die wichtigeren sachen konzentrieren.

**Comment by silvabaum** [comment]
also für uns: Englische Fragen und Antworten auf invisible stellen. (auch in Issue #57)

**Comment by silvabaum** [comment]
done
