### ISSUE TITLE
Main Layer: Auszeichnung der Spezialfragen in der Fragenliste

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#59]
Das war eine Anmerkung von Jana – sie fand es verwirrend, dass es die zwei Wege gibt ohne dass man es vorher weiß wohin sie führen.. Wir haben schon oft drüber gesprochen, gibt es hier noch Vorschläge oder Ideen oder lassen wir es so?

**Comment by silvabaum** [comment]
@claudiascheer @leasievertsen, ich habe gerade gesehen, dass ihr für die Spezialfragen auch eine Plural-Frage formuliert habt. Das ist dabei ja eigentlich nicht nötig. Wenn wir die nur in Singular machen, wären die auch in der Übersicht im singular und man könnte daran erkennen, ob eine Frage mehreren oder nur einer Person gestellt wurde. 
Wie es jetzt ist finde ich es auch recht verwirrend, also, dass man auf einen Frage klickt, die sich an mehrere Personen richtet und dann zum einzelnen Interview kommt.

**Comment by leasievertsen** [comment]
@silvabaum Ja, ich konnte das beim Einpflegen nicht weglassen, ohne beide Versionen konnte ich es nie speichern? @claudiascheer, wie war das bei dir?

**Comment by silvabaum** [comment]
Fragen sind angepasst. Close, oder sollen wir noch über diese Auszeichnung nachdenken? Haben wir ja auch schon sehr oft …

**Comment by leasievertsen** [comment]
vielleicht sollten wir ncohmal ein paar fremde meinungen einholen, wenn wir zb deine eltern oder paul oder tini usw. mal testen lassen

**Comment by claudiascheer** [comment]
Wir können nochmal drüber nachdenken, aber eher nach dem 8. oder?

**Comment by silvabaum** [comment]
ja würde ich auch sagen. erst mal schließen?
