### ISSUE TITLE
Interview Overlay: Leerraum als Abschluss/Footer

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#62]
Wenn das Interview unten zu Ende ist, soll da vllt noch irgendwas kommen? zB ein Leerraum? Damit man auch wirklich weiß, dass das Interview zu Ende ist?

**Comment by silvabaum** [comment]
Ja, ein Leerraum dort wäre gut

**Comment by jensschnitzler** [comment]
how much leerraum? halbe bildschirmhöhe?

**Comment by silvabaum** [comment]
Hört sich ein bisschen viel an. Viertel?

**Comment by jensschnitzler** [comment]
ich werde ein viertel einbauen und dann testen wirs 👍 
notiz an mich selbst:

```
#about-content, #interview-content {
  margin-bottom: 25vh;
  …
}
```

**Comment by jensschnitzler** [comment]
_fixed_
