### ISSUE TITLE
interne Links

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#63]
nur für uns zur Erinnerung, dass wir die noch ordentlich verlinken müssen. In den Interviews sind sie momentan als »blinde« (?) Links angelegt (also Links die zu nichts führen, damit wir wissen wo noch was angelegt werden muss)

**Comment by silvabaum** [comment]
Da alle Interviews eingepflegt sind, können wir die jetzt verlinken, oder nicht? @jensschnitzler: Könnte sich an den IDs noch etwas verändern?

**Comment by jensschnitzler** [comment]
@silvabaum alle ID-related questions an @otcn , please. ich weiss nicht wie diese funktion aufgebaut ist.

**Comment by silvabaum** [comment]
yes, ok, sorry.

**Comment by silvabaum** [comment]
@otcn, können wir die Interviews untereinander schon verlinken?

**Comment by otcn** [comment]
Die ID's werden automatisch an jedes Frage-Antwort-Paar vergeben, sobald ihr es anlegt. Da dürfte sich also nichts mehr dran ändern

**Comment by silvabaum** [comment]
Dann Erinnerung für uns: Interviews verlinken!

**Comment by silvabaum** [comment]
Die drei Verlinkungen innerhalb der Interviews (z.B. von Julia Meer zu Gerda Breuer) sind eingepflegt. 

Für die Verknüpfung von Design und Theorie haben wir ja jetzt noch keine Lösung gefunden. Schaffe wir das noch bis zum 8. oder lieber in Ruhe danach, @claudiascheer und @leasievertsen?

**Comment by claudiascheer** [comment]
Ich würde in Ruhe danach vorschlagen.. bis auf drei Interviews habe ich die Verlinkungen schon angelegt, aber ich glaube von euch hat noch niemand drüber geguckt und ich tippe dass das schon ein Brett ist und lange dauert

**Comment by silvabaum** [comment]
ja, sehe ich auch so. da haben wir ja letztens schon drüber diskutiert und das wirkte komplizierter. dann würde ich das hier erst mal closen?
