### ISSUE TITLE
About Overlay: roter Balken grau möglich?

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#64]
Das About-Overlay ist grau – ist es hier möglich, dass dann auch der notamuse-Balken ganz rechts auch grau wird anstatt rot?

**Comment by jensschnitzler** [comment]
@claudiascheer ja, möglich bestimmt. ist das gewünscht? hat das eine hohe priorität?

**Comment by claudiascheer** [comment]
das haben @leasievertsen und ich überlegt, aber noch nicht mit @silvabaum besprochen, deswegen keine hohe prio ;)

**Comment by silvabaum** [comment]
wär für mich in Ordnung

**Comment by jensschnitzler** [comment]
_fixed_
