### ISSUE TITLE
Interview Overlay: rechte Infoseite nicht scrollbar

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#65]
Der Interviewtext ist scrollbar, die rechte Seite unter dem Bild nicht
> im Screenshot: ich kann nicht lesen, was nach dem Datum kommt
Browser: Firefox

![bildschirmfoto 2017-11-21 um 21 20 46](https://user-images.githubusercontent.com/33512565/33094907-079655f2-cf02-11e7-949d-d4d44de9d8bb.png)

**Comment by jensschnitzler** [comment]
das würde ich euch gerne erstmal zurück überweisen. wie soll das designtechnisch gelöst werden? sollen überhaupt diese ganzen infos unters bild? ein paar infos doppeln sich ja gerade. soll dann dieser infobereich wirklich scrollbar sein oder sind das zu viele voneinander unabhänige scrollbare bereiche? oder soll die bildgröße verkleinern?

**Comment by leasievertsen** [comment]
an sich würde das bild kleiner ja keine lösung sein, weil es trotzdem immer wieder zu dem gleichen problem kommt ja nach fenstergröße oder? irgendwo ist ja immer der punkt wo man sich selbst etwas verdeckt und dann nichts scrollbar ist. aber eigentlich soll der bereich ja fixed sein..:/ hmmm

**Comment by jensschnitzler** [comment]
hi @leasievertsen also man kann schon von einer mindesthöhe des browserfensters ausgehen. ich glaube 640px könnte man da ansetzen. in der mobilen ansicht muss dann wahrscheinlich eh mit der ganzen spalte anders umgegangen werden. ich würde zb sagen, dass man den infos unter dem bild kürzt und das bild eine maximale höhe von 50% der bildschirmhöhe hat.

**Comment by silvabaum** [comment]
@jensschnitzler: hatten wir nicht bei der Entwurfsdatei schon mal besprochen, dass das Bild 80vh hoch sein soll? Am besten wäre es ja, wenn sowohl Breite als auch Höhe vom browserfenster abhängig wären, aber auch das Seitenverhältnis beibehalten würde oO Ginge das?
Sonst könnten wir auch die ganze Seite stufenlos skalierbare machen, dann würde das Problem ja nicht auftauchen, oder?

**Comment by jensschnitzler** [comment]
@silvabaum 80vh ist auf einem laptop oder desktop screen schon extrem groß. ich glaube, zuerst muss für dieses issue das issue #78 gelöst werden …

**Comment by claudiascheer** [comment]
ich habe hier ein beispiel, in dem die rechte zwar scrollbar ist, aber nicht ganz (das datum geht nicht mehr drauf) und in der breite ist es auch scrollbar (das braucht man eigentlich gar nicht oder? dann entsteht sowas wie auf dem Screenshot dass die Inhalte in der Breite angeschnitten werden)
![bildschirmfoto 2017-11-28 um 13 06 16](https://user-images.githubusercontent.com/33512565/33319084-6878c752-d43d-11e7-8ea7-20d2fd69e7ca.png)

**Comment by jensschnitzler** [comment]
_notiz an mich selbst:_

```
.aside-image {
  width: 24vw; /* evtl ganz raus? */
  …
}
.aside-info, .preview {
   …
  padding: 0;
  margin:0;
  overflow-y: scroll;
  overflow-x: hidden;
}
.aside-info figure, .preview figure {
  …
  padding-top: 19px;
}
```

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**
