### ISSUE TITLE
Interview Overlay: Abstände zwischen Head/Intro/Text

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#66]
Die Abstände zwischen Head/Intro/Text sind anders als im Gestaltungs-PDF

**Comment by jensschnitzler** [comment]
hi @claudiascheer , welches gestaltungs-pdf meinst du? meine aktuellste vorlage ist die indesign datei "171002_Web_NEU.indd" im Ordner "_notamuse-material" in der Dropbox. Ist das dasselbe oder gibt es einen neueren Stand?

**Comment by claudiascheer** [comment]
huhu @jensschnitzler, lea und ich haben beim issues-schreiben das pdf notamuse_Web_171002.pdf verwendet, ich tippe mal dass das dann einfach das PDF zu deiner indesign-datei ist

**Comment by jensschnitzler** [comment]
Der Abstand zwischen Headline und Intro ist jetzt:

```
  #about-content h1, #interview-content h1 {
    margin-bottom: 50px;
  }
```

Und der Abstand nach Intro ist jetzt: 

```
  .i-intro {
    margin-bottom: 110px;
  }
```
