### ISSUE TITLE
Interview Overlay: Problem mit Schließsymbol

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#67]
Das Schließsymbol kommt nicht, es bleibt ein Plus-Zeichen (Fehler nur wenn man über Topics kommt, wenn man über die Interviewnavigation kommt, funktioniert es?)

**Comment by jensschnitzler** [comment]
hi @claudiascheer , bin mir nicht ganz sicher, ob ich verstehe, an welcher stelle das problem auftritt … hast du ein screenshot zur hand?

**Comment by claudiascheer** [comment]
Ehrlich gesagt weiß ich auch nicht mehr, was genau das Problem war.. @leasievertsen – weißt du es noch? x)

**Comment by jensschnitzler** [comment]
@claudiascheer @leasievertsen close?

**Comment by silvabaum** [comment]
Anderes Problem mit Schließsymbol: in der Nav wird bei Hover auf Schließ- und Öffnensymbol aus dem Cursor ein Pointer, aber man kann nicht draufklicken, sondern nur auf den Text. Kann das Symbol auch klickbar sein?

**Comment by silvabaum** [comment]
weiterer Bug: Abstand des Symbols zu den Topics ist fehlt

**Comment by claudiascheer** [comment]
![bildschirmfoto 2017-11-28 um 13 02 59](https://user-images.githubusercontent.com/33512565/33318837-7d3ac718-d43c-11e7-971c-ff3fd8534bf5.png)

**Comment by jensschnitzler** [comment]
@silvabaum zu dem problem mit dem abstand: haben wir das gestern schon korrigiert? ansonsten: screenshot plz. verstehe nicht genau, welcher abstand gemeint ist.

EDIT: danke @claudiascheer !

**Comment by jensschnitzler** [comment]
_notiz an mich selbst:_

```
.nav>ul>li {
  …
  max-width: 19vw;
}
```

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**

**Comment by silvabaum** [comment]
@jensschnitzler: was weiterhin nicht funktioniert: 

> in der Nav wird bei Hover auf Schließ- und Öffnensymbol aus dem Cursor ein Pointer, aber man kann nicht draufklicken, sondern nur auf den Text. Kann das Symbol auch klickbar sein?

![bildschirmfoto 2017-11-30 um 00 07 22](https://user-images.githubusercontent.com/33488569/33403957-ae493868-d562-11e7-9929-f9c9462461b5.png)

**Comment by leasievertsen** [comment]
Das scheint jetzt bei mir zu funktionieren!

**Comment by silvabaum** [comment]
Bei mir nicht

**Comment by claudiascheer** [comment]
Bei mir funktioniert es (Firefox)

**Comment by silvabaum** [comment]
Ok, Missverständnis: Klicken auf den Text geht, aber Klicken auf das Symbol nicht. 
@jensschnitzler, wäre es möglich, auch das **Symbol** klickbar zu machen?

**Comment by claudiascheer** [comment]
EDIT: es schließt, wenn ich auf den Text davor klicke (zB. Interviews) aber nicht wenn ich direkt auf das + oder x klicke

**Comment by jensschnitzler** [comment]
👍  das sollte nach dem kommenden upload funktionieren. test + close, please

**Comment by silvabaum** [comment]
Check!
