### ISSUE TITLE
Interview Overlay Image: teilweise verzerrt 

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#68]
Die Fotos sind hier teilweise verzerrt
Browser: Firefox

![bildschirmfoto 2017-11-21 um 21 27 50](https://user-images.githubusercontent.com/33512565/33095139-dcfb8028-cf02-11e7-80a8-4754cfaf18c9.png)

**Comment by jensschnitzler** [comment]
fixed. testen und schließen :-)

**Comment by leasievertsen** [comment]
Bei mir im Chrome (off course inkognito) funktioniert es noch nicht:
<img width="1440" alt="bildschirmfoto 2017-11-23 um 18 15 12" src="https://user-images.githubusercontent.com/33448884/33183927-599c3bfe-d07a-11e7-9038-8ff3a98df4a2.png">
<img width="1440" alt="bildschirmfoto 2017-11-23 um 18 15 19" src="https://user-images.githubusercontent.com/33448884/33183928-59cc8d18-d07a-11e7-88dd-d26995383485.png">

**Comment by jensschnitzler** [comment]
sorry, hatte den aktuellen stand noch nicht hochgeladen. JETZT ist er aber da! :-)

**Comment by claudiascheer** [comment]
Bei mir funktioniert es noch nicht, oder vielleicht mach ich auch was falsch ;)

![bildschirmfoto 2017-11-24 um 11 17 18](https://user-images.githubusercontent.com/33512565/33206000-25fb7cda-d109-11e7-97a1-e40599c6a827.png)

**Comment by jensschnitzler** [comment]
weeird … dein browser sieht nicht nach inkognito/privatem modus aus, oder doch? sonst versuch mal deinen "browser cache zu löschen".

**Comment by silvabaum** [comment]
ich hab es heute in firefox, safari und Chrome getestet und es war richtig

**Comment by jensschnitzler** [comment]
ich close das ticket dann jetzt. sollte der fehler irgendwo noch einmal beobachtet werden, kann es einfach wieder geöffnet werden.
