### ISSUE TITLE
Navigation Interviews: Image-Hover angeschnitten

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#69]
Beim Hover über das Interview wird das Bild zwar angezeigt, aber angeschnitten, siehe Screenshot (die rechte Frau ist abgeschnitten)
Browser: Firefox

![bildschirmfoto 2017-11-21 um 21 29 35](https://user-images.githubusercontent.com/33512565/33095234-34fdeafe-cf03-11e7-8590-957cb79ae894.png)

**Comment by jensschnitzler** [comment]
_fixed._ testet, ob es jetzt funktioniert bzw. es euch jetzt so gefällt, wie es gefixed ist, und falls es gut ist, schließt das issue hier.

**Comment by silvabaum** [comment]
crome: fixed
safari: fixed
firefox: fixed
