### ISSUE TITLE
GitHub -> FTP -> dev.notamuse.de

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#7]
Hi!

Bisher habe ich die Daten auf "dev.notamuse.de" via Filezilla hochgeladen. Ich habe aber das Gefühl, dass es einen besseren, automatisierten Weg geben könnte, um die Inhalte des GitHub Master-Branchs auf den Production Server zu transferieren. Vielleicht haben Malte oder Jana da einen guten Tipp.

**Comment by electricgecko** [comment]
hi @jensschnitzler,
ja - das vermutest du schon richtig. prinzipiell kannst du natürlich auch vom server aus ein aktualisiertes repo von github ziehen. in der praxis ist das allerdings nicht ganz so simpel, da in der regel diverse dinge (JS, CSS-komponenten etc.) kompiliert werden müssen, zum beispiel mit [grunt](http://gruntjs.com) oder [gulp](http://gulpjs.com).

weiterhin muss auf dem server natürlich git laufen, was bei günstigen shared servern selten der fall ist und aufgrund fehlender berechtigungen auch nicht geändert werden kann.

that said – es gibt diverse anleitungen zu diesem thema, zum beispiel diese hier: https://gist.github.com/oodavid/1809044. du kannst dir auch mal deploybot anschauen, das ist ziemlich nice und deckt deinen usecase ebenfalls ab: https://deploybot.com.
