### ISSUE TITLE
Interview Overlay: Position Text Unit

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#70]
Text Unit öffnet sich auf der Höhe der jeweiligen Text Unit, die ich bei der letzten aufgehört habe zu lesen und nicht wieder am Anfang von Interview Overlay (zB ganz unten, wenn ich das Interview, was ich davor gelesen habe, bis ganz unten gescrollt habe)

**Comment by jensschnitzler** [comment]
sollte mit dem kommenden upload gefixt sein. testen und schließen plz

**Comment by silvabaum** [comment]
fixed
