### ISSUE TITLE
Interview Overlay: Webadressen ohne http://

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#74]
Info (rechte Seite): Webadresse nicht mit http:// anzeigen

**Comment by jensschnitzler** [comment]
Hi @zweipi ,

ich verzweifle gerade an einem wahrscheinlich banalem problem :-)

Mit "classy-links.js" will ich dafür sorgen, dass (1) die externen links im interview eine bestimmte class erhalten und (2) ggf. das "http://" vor URLs entfernt wird. An und für sich scheint der Code zu funktionieren (auf der Main Layer), aber ich weiss nicht, wann ich die Funktion "classyLinks()" callen muss, damit auch auf den Interview Overlays die Links geändert werden … 

Ich habs zuerst am ende von "function projects(uid) { … }" eingesetzt, aber das funktioniert irgendwie nicht. Hättest du eine Idee?

Testweise habe ich es gerade so eingerichtet, dass die Funktion gecalled wird wenn man das Interview schon geöffnet hat und irgendwo auf das overlay klickt :-D

**Comment by jensschnitzler** [comment]
@zweipi es funktioniert :-) 

es war ein scope problem: in classy-links.js war die funktion classyLinks innerhalb der funktion von document.ready definiert und konnte deshalb nicht in script.js erkannt werden …

@silvabaum @leasievertsen @claudiascheer 
"https://" und "http://"  vor den dargestellten links und ggf. ein "slash" am ende der adresse werden jetzt automatisch entfernt.
