### ISSUE TITLE
allgemein: mobile Ansicht

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#76]
He Hasen, ich habe mal eine mobile Variante versucht, siehe PDF anbei!

Dazu noch ein paar Anmerkungen: 
1. Der Overlay macht meiner Meinung nach nur auf der Startseite Sinn, da könnte es gut klappen, ansonsten werden zB die Interviewseiten einfach ganz rot. 
2. Dadurch fällt der Punkt Themen weg, seine Funktion übernimmt das notamuse-Logo (wie ein Home-Button). 
3. Es gibt mobil ja keinen Hover, deswegen hab ich + und x immer sichtbar gemacht 
4. Als Menü hab ich mal ein klassisches gemacht, wie man es bei mobilen Seiten vielleicht erwartet. 
5. Es gibt nur noch 2 Schriftgrößen. 
6. Größen und Abstände sind jetzt noch nicht ins feinste Detail ausgearbeitet, aber vielleicht kann man sich den Ablauf ein bisschen besser vorstellen?

[20171122_Mobile_cs.pdf](https://github.com/otcn/notamuse/files/1496429/20171122_Mobile_cs.pdf)

Ich hab versucht, alles ganz einfach und technisch nicht so kompliziert zu machen... Könnt ihr euch ja mal angucken. Ich versteh total wenn das bis zum 8. nicht fertig sein kann, aber vielleicht gibt es ja doch eine Möglichkeit dass man die Seite auf dem Handy zumindest ansatzweise benutzen kann ;)

**Comment by silvabaum** [comment]
Haben wir ja gestern schon besprochen, aber vielleicht hier noch mal der Übersichtlichkeit halber: 
Der Entwurf ist super, nur noch ein paar Anpassungen der Schrift: 
Fließtext größer und vllt dann auch die andere Größe; 
Ist die größere Schrift und "notamuse" gleich groß? wenn nicht lieber anpassen; 
Laufweite anpassen; 
Interview-Head weiß; 
den Abstand rechts neben dem Fließtext raus; 
die Schließ- und Öffnenzeichen gibt es als Glyphen in der Schrift (weiß nich ob die das im Entwurf schon waren, ist aber für den Entwurf vllt auch nicht so wichtig); 
und Fragen und Links auf dem Intro-Overlay wollten wir rausnehmen

**Comment by claudiascheer** [comment]
das Intro-Overlay kann man sowohl nach oben rauswischen als auch über das kreuz schließen

@silvabaum: die große Schrift und notamuse ist grade noch nicht gleich groß, Schliess- und Öffnungszeichen sind manuel angelegt und nicht als Glyphen eingefügt

**Comment by silvabaum** [comment]
ich Close das hier mal, denn das issue doppelt sich ja mit ein paar anderen
