### ISSUE TITLE
Overlay/Mainlayer: Themen in extended?

### ISSUE THREAD

**Issue by claudiascheer** [otcn/notamuse#77]
Ich hab Manu grad die Seite gezeigt und er hatte einen kleinen Vorschlag, über den man mal nachdenken kann:

Wenn ich neu auf die Seite komme und das rote Zitat-Overlay erscheint, fand er, dass das extended-»Themen«, das drunter liegt, wie ein Fehler aussieht. Ihm würde es helfen, wenn das da die linke Navi komplett in regular steht, und Themen sich erst extended, wenn man den roten Overlay wegklickt. 

Also, nichts dringendes oder extrem wichtiges, aber ich wollte es mal weiterleiten ;)

**Comment by silvabaum** [comment]
Sollte auch nicht extended sein

**Comment by jensschnitzler** [comment]
sollte in der nächsten version gefixt sein. gerne testen, sobald sie hochgeladen ist und ggf. dieses issue schließen.

**Comment by silvabaum** [comment]
fixed, allerdings sollte es dann ausgezeichnet sein, wenn man den Intro-Overlay wegklickt. Oder @claudiascheer, @leasievertsen? Geht das?

**Comment by leasievertsen** [comment]
ne!

**Comment by claudiascheer** [comment]
bei mir gehts auch nicht

**Comment by jensschnitzler** [comment]
@silvabaum @leasievertsen status? close?

**Comment by leasievertsen** [comment]
bei mir gehts nicht

**Comment by jensschnitzler** [comment]
cache geleert? was genau geht nicht? welcher browser?

**Comment by leasievertsen** [comment]
ja. chrome
es ist nicht extended nach dem schließen

**Comment by jensschnitzler** [comment]
aachso, das war ein missverständnis. ich habe folgenden teil der diskussion so verstanden, dass das schließen des overlays den topic-button nicht aktivieren soll:

![bildschirmfoto 2017-11-28 um 16 15 39](https://user-images.githubusercontent.com/14975858/33327349-8f88e786-d457-11e7-8049-35fdd65d6105.png)

**Comment by silvabaum** [comment]
hat Jens gerade gefixed, kommt mit nächstem upload
