### ISSUE TITLE
Interview Aside-Info Text

### ISSUE THREAD

**Issue by jensschnitzler** [otcn/notamuse#78]
Hi, ein angehängter Screenshot zeigt den Entwurf, der andere zeigt den derzeitigen Stand auf der Website. 

1. Soll die Reihenfolge nach wie vor "Name, Website, Ort" bleiben?
2. Soll der Ort in der Form "Stadt, Land" dargestellt werden?
3. Soll der Ort überhaupt doppelt aufgeführt werden? 

<img width="799" alt="bildschirmfoto 2017-11-23 um 17 58 14" src="https://user-images.githubusercontent.com/14975858/33183399-ff509d5e-d077-11e7-8eea-f38508cdf68b.png">

![bildschirmfoto 2017-11-23 um 17 58 20](https://user-images.githubusercontent.com/14975858/33183513-6d0023b0-d078-11e7-90f3-ffeac630c92d.png)

**Comment by silvabaum** [comment]
@leasievertsen, @claudiascheer, wenn wir diesen Satz schreiben brauchen wir den Ort oben eigentlich nicht mehr, oder? Oder wir lassen ihn oben und schreiben statt dem Satz nur das Datum. Bei Anna Haas z.B. doppelt sich ja auch noch ihr Name (mit der Überschrift ist er dann sogar drei mal da). Was meint ihr?

**Comment by claudiascheer** [comment]
ja, ich finde auch, entweder satz und oben ohne ort oder oben mit ort und unten nur datum – ich finde oben mit ort und drunter dann nur das datum eigentlich eine kurze und knappe und gute lösung! das mit der namensdopplung lässt sich wahrscheinlich nicht vermeiden, ist aber grade bei anna haas auch ein extremes beispiel oder? bzw. stehen da immer designerinnennamen, studionamen, website oder nur designerinnennamen und website?

**Comment by silvabaum** [comment]
Ja, ich finde Name, Web, Stadt (mit Land?), Datum auch gut

**Comment by silvabaum** [comment]
@jensschnitzler: Korrektur: nicht NAME, Web, usw. sondern STUDIONAME, Web, usw.

**Comment by leasievertsen** [comment]
@silvabaum @claudiascheer 
Aber versteht man das es darum geht, wann das Interview geführt wurde, wenn da einfach nur das Datum steht?

**Comment by silvabaum** [comment]
ich glaube schon. bei Artikeln bei Onlinezeitungen oder blogs steht doch auch irgendwo das Datum und dann denkt man, dass das von dann ist, oder?

**Comment by leasievertsen** [comment]
Aber würde dann zb "via email" oder ähnliches ganz wegfallen?
Das fänd ich nämlich sehr wichtig, das unterscheidet die interviews auch irgendwie, und wir vermitteln nciht den falschen eindruck, als wären wir überall vor ort gewesen, das fänd ich komisch

**Comment by silvabaum** [comment]
Wir könnten auch Studioname, Web, Satz machen

**Comment by leasievertsen** [comment]
Haben wir denn alle Interviews an den "richtigen" Orten geführt? Eigentlich ja oder? Dann fänd ich das ok

**Comment by silvabaum** [comment]
außer Michelle, die haben wir in Hamburg geführt und das interview war in Hamburg

**Comment by silvabaum** [comment]
Ok, das heißt wir müssen uns entscheiden, ob wir den Ort an dem die Person lebt angeben wollen oder den, an dem das Interview geführt wurde. Wenn es der Interview-Ort sein würde ich den Satz nehmen wollen, denn wenn der Ort ohne Kontext aufgeführte ist, würde ich annehmen, dass das der Wohn-, bzw. Arbeitsort ist. Was meint ihr?

**Comment by claudiascheer** [comment]
Ich würde den Ort verwenden, an dem das Studio ist.. Ist ja bei allen so außer bei Michelle, und ob da jetzt Berlin oder Hamburg steht, fällt wahrscheinlich gar nicht auf

**Comment by silvabaum** [comment]
Allerdings könnte dann bei den mail-interviews auch nicht stehen dass die per mail sind … finde es eigentlich auch interessant zu wissen wie die Interviews entstanden sind … kann mich aber mit beiden Versionen anfreunden

**Comment by leasievertsen** [comment]
Ich finde es gut, zu wissen wo die entstanden sind. Das hat mich beim Buch von WiGD zb voll interessiert, weil ich mir die Interviewsituationen dann viel besser vorstellen konnte. Können wir die Dopplung nicht einfach so lassen? Mich stört die auch nicht besonders, vor allem wenn das eine mal der Satz ausgeführt wird. Wenn man da den Namen weglässt, ist es auch etwas weniger dopplung.

Anna Haas
Zürich, Schweiz
annahaas.de

Das Interview wurde am X.X.17 in Zürich geführt.

**Comment by silvabaum** [comment]
Ja, so finde ich es gut. und der erste Ort ist dann der Wohnsitz

**Comment by silvabaum** [comment]
@jensschnitzler, können wir in der Aside-Info bitte folgende Änderungen haben?

1. Studioname (dazu brauchen wir ein neues Feld im Panel)
2. Wohnort (neues Feld im Panel)
3. "Das Interview wurde am X.X.17 in Interviewort geführt."

![bildschirmfoto 2017-12-01 um 10 48 58](https://user-images.githubusercontent.com/33488569/33477398-d54b3794-d685-11e7-8cc7-132d63fff036.png)

**Comment by claudiascheer** [comment]
finde ich auch eine gute Lösung :)

**Comment by claudiascheer** [comment]
Ich weiß nicht ob wir darüber schon gesprochen haben, aber finde ich grad irritierend: Haben wir in der rechten Spalte die externen Links bewusst nicht als solche ausgezeichnet? @leasievertsen @silvabaum 

![bildschirmfoto 2017-12-01 um 18 29 56](https://user-images.githubusercontent.com/33512565/33495216-ce06e772-d6c5-11e7-825f-04337761d917.png)

**Comment by claudiascheer** [comment]
oder ist es ok weil es offensichtlich ein externer link ist?

**Comment by silvabaum** [comment]
nee, haben wir vergessen

**Comment by jensschnitzler** [comment]
@silvabaum sollte ab dem nächsten upload im panel verfügbar sein!
@claudiascheer die links in der aside info sind jetzt als externe links ausgezeichnet!
für neue fehler bitte neues issue anlegen :-)

**Comment by silvabaum** [comment]
danke!
Allerdings ist der Satz "Das Interview mit xyz wurde am X.X.17 in xxx geführt." noch nicht umformuliert in "Das Interview wurde am X.X.17 in xxx  geführt."

**Comment by jensschnitzler** [comment]
👍  ist entfernt. nach dem nächsten upload testen und schließen, bitte.

**Comment by silvabaum** [comment]
check!
