### ISSUE TITLE
Main Layer: Hover auf aktive Fragen

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#79]
Fragen mit Hovereffekt haben andere Breite als aktive Fragen (geöffnete), sollte gleich sein. So umbrechen sie nämlich neu, wenn man auf die geöffnete Frage hovert; das sollte nicht passieren (Screenshot 1 ohne hover, screenshot 2 mit hover)

![bildschirmfoto 2017-11-24 um 15 53 37](https://user-images.githubusercontent.com/33488569/33215355-b6501090-d12f-11e7-9b51-0309e7177f33.png)

![bildschirmfoto 2017-11-24 um 15 48 07](https://user-images.githubusercontent.com/33488569/33215279-742a82fe-d12f-11e7-95d1-f37b39ed7973.png)

**Comment by jensschnitzler** [comment]
Die inaktiven Fragen haben jetzt eine maximale Breite von 54% des Viewports (Browserfensters) und die aktiven/gehoverten Fragen eine maximale Breite von 66% des Viewports. 

Damit sollte das Problem hoffentlich gefixt sein :-)

```
  .question-title a:first-child {
    max-width: 54vw;
    display: block;
  }
  .question-title a:first-child:hover, .question-title a:first-child.active {
    max-width: 66vw;
  }
```

**Comment by silvabaum** [comment]
Eine Frage umbricht noch neu bei Hover: inaktive question-title bitte auf 53vw max-with stellen

**Comment by jensschnitzler** [comment]
_notiz an mich selbst:_

```
.question-title a:first-child {
    max-width: 53vw;
    …
}
```

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**

**Comment by leasievertsen** [comment]
bei einigen skalierungen erscheinen mir einige fragen noch zu eng?
(getestet in firefox)
<img width="843" alt="bildschirmfoto 2017-11-28 um 22 52 57" src="https://user-images.githubusercontent.com/33448884/33346134-fcf64250-d48e-11e7-8e20-92b517dc3652.png">
<img width="1440" alt="bildschirmfoto 2017-11-28 um 22 52 07" src="https://user-images.githubusercontent.com/33448884/33346135-fd2827ac-d48e-11e7-914b-a15c14c5cdb1.png">

**Comment by silvabaum** [comment]
Fragen haben vw, Plus und Kreuz festen Wert nach rechts, daher stoßen sie unweigerlich irgendwann zusammen. Bitte Symbolen auch prozentualen Abstand geben, ggf. ins Padding der Frage legen.

aktuell:
![bildschirmfoto 2017-11-29 um 09 31 48](https://user-images.githubusercontent.com/33488569/33389388-f8d5ddda-d532-11e7-9054-f0fdc2061bae.png)

besser:
![bildschirmfoto 2017-11-29 um 09 31 06](https://user-images.githubusercontent.com/33488569/33389420-0d816fba-d533-11e7-9ced-298f99929586.png)

**Comment by silvabaum** [comment]
fixed!
