### ISSUE TITLE
About Overlay: Textabsätze

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#81]
Die Abstände zwischen den Absätzen im Abouttext sind zu groß, besser ganz raus oder maximal einen Leerzeile Abstand. Sind im Panel mit `<br>` eingegeben.

![bildschirmfoto 2017-11-24 um 17 20 50](https://user-images.githubusercontent.com/33488569/33218281-4ebdebac-d13c-11e7-8e0d-70a816a604ac.png)

**Comment by jensschnitzler** [comment]
Mit dem Untersuchen-Tool sieht man, dass die Abstände nur durch den manuellen Umbruch im Backend entstehen. Jedes `<br>` ist ein harter Zeilenumbruch:


![bildschirmfoto 2017-11-24 um 17 27 43](https://user-images.githubusercontent.com/14975858/33218361-db494742-d13c-11e7-8a69-a4ad50a4afd4.png)

**Comment by silvabaum** [comment]
fixed
