### ISSUE TITLE
Main Layer: last Answer

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#82]
Zwischen letzter Antwort und Linie bitte etwas Abstand einfügen

![bildschirmfoto 2017-11-24 um 15 48 38](https://user-images.githubusercontent.com/33488569/33218363-dc4e903e-d13c-11e7-87ca-1a2cffcc36be.png)

**Comment by jensschnitzler** [comment]
notiz an mich selbst:

```
.answer-item:last-of-type {
  margin: 27px 0px 27px 0px;
  …
}
```

**Comment by jensschnitzler** [comment]
_fixed_
