### ISSUE TITLE
Navigation Bug: Nav-Elemente verschwinden (Safari 11.0.1)

### ISSUE THREAD

**Issue by otcn** [otcn/notamuse#83]
Hey,
Wenn ich in der Nav die Liste mit den Fragen öffne, scrolle und dann die Fragen (per Click auf Fragen) wieder schließe, verschwinden die oberen 3 Navigationspunkte.

![bildschirmfoto 2017-11-27 um 09 19 10](https://user-images.githubusercontent.com/24541531/33257214-aa82d3c4-d355-11e7-909d-709458338ad8.png)

**Comment by jensschnitzler** [comment]
sollte mit dem nächsten upload gefixt sein. bitte testen und issue schließen

**Comment by silvabaum** [comment]
fixed
