### ISSUE TITLE
Firefox, Scrollbalken

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#84]
Hallo, in Firefox haben die Hauptbereiche (Main Layer Topic-Bereich, Interview Overlay, About Overlay) einen Scrollbalken:

![bildschirmfoto 2017-11-27 um 15 15 08](https://user-images.githubusercontent.com/33488569/33270975-2576f74c-d386-11e7-8eac-1dcd58b95222.png)

**Comment by jensschnitzler** [comment]
@silvabaum bei mir im firefox funktioniert es, deshalb konnte ich meinen fix jetzt nicht testen. ich hoffe es funktioniert. nach dem nächsten upload bitte testen und ggf issue schließen :-)

**Comment by silvabaum** [comment]
bei mir ist es noch genauso. es ist auch kein ganzer Balken, genau genommen ist der Balken nicht da, sondern nur der Streifen, in dem sonst der Balken ist (wie im screenshot oben)

**Comment by claudiascheer** [comment]
@jensschnitzler bei mir ist es auch noch sichtbar, hier ein screenshot, bei dem im interview-layout die rechte infospalte so scrollbar ist (mit scrollbalken)

![bildschirmfoto 2017-11-28 um 12 48 26](https://user-images.githubusercontent.com/33512565/33318340-9c11b3b0-d43a-11e7-8d9f-8d9cd07c5409.png)

**Comment by claudiascheer** [comment]
auf der Startseite, wie bei Silvas Screenshot, hab ich keinen Balken mehr

**Comment by jensschnitzler** [comment]
_notiz an mich selbst:_

```
.aside-info, .preview {
  …
  height: auto;
  max-height: 100vh;
}
```

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**
