### ISSUE TITLE
Main Layer/Interviewee-title

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#87]
Vor dem Interviewee-title fehlt der Pfeil , genauso wie vor den Fragen und Inertviewees in der Nav.

**Comment by jensschnitzler** [comment]
der pfeil soll in der navigation unter "interivews" nur bei hover erscheinen und nach rechts ausgerückt sein. der alphabetische registermarker soll ggf zum pfeil werden. bei hover werden die listenelemente extended und nicht unterstrichen.

interviewee titel sollen den pfeil immer vorangestellt bekommen und sich beim hover nicht verändern.

**Comment by silvabaum** [comment]
![bildschirmfoto 2017-11-27 um 18 57 34](https://user-images.githubusercontent.com/33488569/33281261-e92db40a-d3a4-11e7-885a-a323711a8b5d.png)

**Comment by jensschnitzler** [comment]
👍 FIXED nach dem nächsten upload bitte testen und schließen
