### ISSUE TITLE
Interviewee-title Inhalt

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#88]
@leasievertsen @claudiascheer, was wollen wir im Antworttitel stehen haben? Nur die Namen oder die Angaben wie in der Nav (also mit Beruf und Studio)?

![bildschirmfoto 2017-11-27 um 18 14 24](https://user-images.githubusercontent.com/33488569/33279524-1f2cae22-d39f-11e7-8b1c-86aa9fdaf9da.png)

**Comment by leasievertsen** [comment]
Ich fänd alle Angaben schöner, was meint ihr? Ich stelle mir vor, dass das direkt mehr Interesse weckt, etwas anzuwählen.. @silvabaum, @claudiascheer

**Comment by claudiascheer** [comment]
@silvabaum @leasievertsen da stimme ich lea zu, ich glaube ich fände es persönlich auch interessanter immer direkt mit einem namen ein studio verknüpfen zu können

**Comment by silvabaum** [comment]
ja, finde ich auch. 

@jensschnitzler @otcn: Kann in den Interviewee-titles bitte der Navigation Title stehen?

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen por favor.
