### ISSUE TITLE
Impressum Text

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#89]
Erinnerung an uns: Impressumstext anpassen, ist noch ein Blindtext

**Comment by silvabaum** [comment]
Wollen wir den Urheberrechtsteil haben oder nicht (Femke)? Oder können wir ihn irgendwie anpassen, z.B. Urheberrecht liegt bei uns, aber den Teil mit schriftlicher Zustimmung raus?

![bildschirmfoto 2017-11-27 um 18 32 09](https://user-images.githubusercontent.com/33488569/33280136-652c6a78-d3a1-11e7-83df-fdc211ea88da.png)

**Comment by leasievertsen** [comment]
Das anzupassen fänd ich gut.

**Comment by claudiascheer** [comment]
Femke haben wir zugesagt dass ihr text frei verfügbar sein wird.. den aktuellen finde ich ein bisschen zu hart, weil es ja eigentlich in unsrem sinne ist, dass sich das verbreitet, damit sich was ändert oder?

**Comment by claudiascheer** [comment]
Femke haben wir zugesagt dass ihr text frei verfügbar sein wird.. den aktuellen finde ich ein bisschen zu hart, weil es ja eigentlich in unsrem sinne ist, dass sich das verbreitet, damit sich was ändert oder? deswegen finde ich eine anpassung auch gut!

**Comment by silvabaum** [comment]
ja, finde ich so auch zu hart, das war eine vorlage aus dem netz. Aber du hast da im doc noch was gemacht, oder Claudi?

**Comment by claudiascheer** [comment]
Im Doc (Website > Impressum) liegt ein knapperer Entwurf zum Impressum
