### ISSUE TITLE
Nav Questions springen nicht zur richtigen Frage

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#90]
Der Weg über die Fragen in der Nav funktioniert nicht mehr. Wenn das Topic der Frage nicht geöffnet ist passiert gar nichts, wenn es geöffnet ist springt etwas, aber nicht zur richtigen Frage.

**Comment by leasievertsen** [comment]
Bei mir funktionieren die Spezialfragen noch, es scheint als beträfe das nur die Katalogfragen?

**Comment by leasievertsen** [comment]
+ auch nicht unbedingt zur richtigen Person

**Comment by otcn** [comment]
Liegt's vielleicht daran @jensschnitzler ?
![bildschirmfoto 2017-11-28 um 12 26 41](https://user-images.githubusercontent.com/24541531/33317508-a8c85d3c-d437-11e7-936d-ebbe3e77a9ff.png)

**Comment by jensschnitzler** [comment]
sieht verdächtig aus, ich schau mal rein!

**Comment by jensschnitzler** [comment]
das problem scheint vielschichtig zu sein :-D

1. das beim klick auf eine reguläre frage in der navigation **nicht auf die richtige art und weise** zur frage in der topics liste gescrollt wird ist ein jquery problem. hier muss ich den code noch optimieren.

2. das beim klick auf eine reguläre frage zu einer **falschen frage** in der topics liste gescrollt wird bzw. beim klick auf eine spezialfrage ein **falsches interview** geöffnet wird, könnte ein php/kirby fehler sein.

@otcn im screenshot verlinkt die frage "achtet ihr auf ein … ?" auf das interview von simone und corina. es handelt sich bei der frage tatsächlich um eine spezialfrage, aber sie gehört zu franziska parschau.

![bildschirmfoto 2017-11-28 um 23 35 46](https://user-images.githubusercontent.com/14975858/33348024-132518e8-d495-11e7-8e8a-6f99448e35c9.png)

**Comment by otcn** [comment]
@jensschnitzler Interessant ist: Scheinbar verlinkt jede Spezialfrage auf das Interview von Simone und Corina.

@silvabaum @jensschnitzler Das Problem bestand aber schon bevor ich mich an die alphabetische Sortierung gesetzt habe, oder?

**Comment by silvabaum** [comment]
@otcn, ja, das mit den Interviews ist Lea vor zwei Tagen schon aufgefallen

**Comment by otcn** [comment]
Hey @jensschnitzler 

Ich bin mal im Commit-Verlauf zurückgesprungen, um zu schauen, wann die Funktion kaputt geht. Scheinbar ist das mit deinem Commit "archived jens-script.js" (23.11.17) passiert. Bei dem Stand davor war noch alles okay. 
Scheint also vielleicht doch eher ein jQuery-Ding zu sein?

![bildschirmfoto 2017-11-29 um 10 32 43](https://user-images.githubusercontent.com/24541531/33368103-02d1f7b6-d4f1-11e7-982f-9a443323b1f2.png)

**Comment by janareddemann** [comment]
See #55

**Comment by jensschnitzler** [comment]
👍 ich glaube ich habe es gefixt. checkt es nach dem nächsten update mal aus und testet, schließt, etc, merci

**Comment by leasievertsen** [comment]
Bei mir funktionieren die Fragen, die in dem Topics-Bereich etwas ansprechen. Die Spezialfragen öffnen das korrekte interview, aber oben in der Einleitung und nicht an der entsprechenden Stelle des Interviews. (Da könnte man auch erstmal so mit leben finde ich, falls das nicht zu fixen ist)

Wir können diese Isssue closen, die Spezialfragenissue #55 gibt es ja noch

**Comment by silvabaum** [comment]
funktioniert gut!
