### ISSUE TITLE
Neuladen zeigt Intro-Overlay trotz anderer URL-Endung

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#91]
Wenn man sich im About- oder Interview-Overay befindet und die Seite neu lädt, behält sie die URL-Endung (z.b: notamuse.de/about), zeigt aber nicht die entsprechende Seite an, sondern das Intro-Overlay.

![bildschirmfoto 2017-11-27 um 22 07 44](https://user-images.githubusercontent.com/33488569/33289313-6d4fdb22-d3bf-11e7-8d0f-7b8168953007.png)

**Comment by janareddemann** [comment]
Das kann in der `function init(){}` definiert werden. Als ich das gecshreiben hatte, hatte der Intro-Container noch von Haus aus .hidden dabei, daher stimmt es jetzt nicht mehr.
Aber die Logik bleibt die gleiche:

```
function init(){
        var uid = History.getState().hash.split('?')[0].substring(1);
        if (uid.length <= 0){  
            // if it is not a subpage
        }
        else if (uid == 'about'){
            // if it is the about page
        }
        else{
            // if it is a subpage
        }
    }
```

**Comment by jensschnitzler** [comment]
👍  sollte mit dem nächsten upload gefixt sein. testen und schließen por favor.

**Comment by silvabaum** [comment]
works!
