### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#92]
Ich habe die Seite auf dem iPhone geöffnet und komme nicht über das Intro-Overlay hinaus, da ich es nicht weg-swipen kann. In den Bereich darunter tippen geht nicht, da dort eine Funktionsleite ist. Die rote Fläche könnte noch verkürzt werden und swipen wäre auch super!

**Comment by jensschnitzler** [comment]
Bitte konzipiert erstmal die mobile Seite ohne Gesten (Swipe etc). 

Irgendwann können wir das hiermit ergänzen, ist aber eine ganz neue Baustelle:
https://hammerjs.github.io/

**Comment by claudiascheer** [comment]
im entwurf ist ein schließelement (x) angelegt, oben im Header neben dem Logo. Könnte man es erstmal damit lösen?

**Comment by silvabaum** [comment]
Und die rote Fläche kürzer machen, da ist unten ja eh kein Inhalt mehr drauf, dann kann man es auch wegblicken, wenn man in den weißen Bereich darunter tippt.

**Comment by leasievertsen** [comment]
ja, das finde ich auch einen guten Vorschlag. da wundert man sich eher über die rote fläche.

**Comment by silvabaum** [comment]
@jensschnitzler, hier ein paar Mobile-Korrekturen:

**Intro-Overlay:** kürzer, sodass man mehr weiße Fläche darunter sieht; Schließsymbol rechts im Header

Höhe:
```
@media only screen and (max-width: 768px)
mobile.css:70
.overlay {
    display: block;
    width: 100vw;
    height: 75vh;
```

**Main-Layer:** Nav-Burger rechts im Header (ich lege gleich einen an); Abstand zu den Seiten größer:
```
@media only screen and (max-width: 768px)
mobile.css:175
.answer-item {
    padding: 2vh 4vw;

@media only screen and (max-width: 768px)
mobile.css:163
.topic-title {
    padding: 2vh 4vw;

@media only screen and (max-width: 768px)
mobile.css:166
.question-title {
    padding: 2vh 4vw;
```

**Nav:**  Inhalt über die gesamte Breite und Abstand zur Seite anpassen:

Über die gesamt Breite habe ich nicht ganz hinbekommen; hier was ich gefunden habe (Änderung der width):
```
@media only screen and (max-width: 768px)
mobile.css:120
.nav > ul > li {
    margin: 0px;
    padding: 2vh 2vw;
    width: 96vw;

.nav-mode #nav-frame > #nav > ul > li {
    max-width: 96vw;

.sub > ul {
    padding: 12px 0 0 2vw;
    overflow-x: visible;
    flex-wrap: wrap;
    display: flex;
    position: relative;
    width: 96vw;

.sub * {
    max-width: 96vw;
``` 
Dazu muss glaube ich noch das a-Element angepasst werden, aber das hat irgendwie nicht funktioniert (vielleicht ist das auch alles falsch da oben^^)
So sah mit der obigen Änderung bei mir aus:

![bildschirmfoto 2017-11-30 um 10 46 41](https://user-images.githubusercontent.com/33488569/33424319-c964cdc0-d5bb-11e7-9731-3f26dd3ba1c8.png)


Abstand zur Seite:
```
@media only screen and (max-width: 768px)
mobile.css:109
.nav {
    height: auto;
    width: 100vw;
    padding: 10vh 4vw;

@media only screen and (max-width: 768px)
mobile.css:120
.nav > ul > li {
    margin: 0px;
    padding: 2vh 0vw;
```

**Interview-Overlay und About-Overlay:** kein Overlay, sondern neue Seite (Fläche nicht verkürzt, sondern bis zum unteren Bildrand, schließen über Symbol oben rechts; Bild Quadratisch unter Headline positionieren, über gesamte Breite

```
@media only screen and (max-width: 768px)
mobile.css:70
.overlay {
    display: block;
    width: 100vw;
    height: 100vh;
```
Bild jetzt:

![bildschirmfoto 2017-11-30 um 10 49 40](https://user-images.githubusercontent.com/33488569/33424462-38616792-d5bc-11e7-8886-9679942d3e94.png)


**Überall: 2 Schriftgrößen:** 1. Größe: Logo, nav-buttons, topic-titles, h1; 2. Größe: question-titles, p; 

Größe 1 bitte größer als bisher, z.B.:
```
@media only screen and (max-width: 768px)
mobile.css:16
.marquee p, .marquee a {
    font-size: 34px;

@media only screen and (max-width: 768px)
mobile.css:11
.topic-title a {
    font-size: 34px;

@media only screen and (max-width: 768px)
mobile.css:6
h1 {
    font-size: 34px;
    line-height: 32px;
```
Nav-buttons sind bisher so groß wie questions-titles, haben wir im Entwurf aber in Größe 1 angedacht:
```
@media only screen and (max-width: 768px)
mobile.css:153
.nav > ul > li > a {
    margin: 0px;
    padding: 0px;
    font-size: 34px !important;
```

**Comment by claudiascheer** [comment]
Ich komme leider im Moment mobil nicht über den roten Startscreen hinaus! Beim Zitat habe ich doppelte Anführungszeichen: »»Zitat««

**Comment by silvabaum** [comment]
Bei wessen Zitat sind die doppelten Anführungszeichen? Die haben wir dann mit eingepflegt.

**Comment by claudiascheer** [comment]
Ich habs eben bei Julia Meer gesehen!

**Comment by silvabaum** [comment]
ok, ich dachte ich hätte es da schon rausgemacht aber viellicht ist es mit einem update verloren gegangen. Bin eh gerade im Panel und kann es ändern.

**Comment by janareddemann** [comment]
`get_browser(navigator.userAgent);`
