### ISSUE TITLE
Letter-Spacing mittlere Schriftgröße

### ISSUE THREAD

**Issue by silvabaum** [otcn/notamuse#93]
Soweit ich es mit dem Untersuchen-Tool erkennen konnte, ist die Laufweite der mittleren Schriftgröße noch nicht angepasst. Weiß auf Rot hat sie in Indesign -10, schwarz auf Weiß -15. Das ist vermutlich nicht eins zu eins in Pixel übersetzbar, oder? Aber als Anhaltspunkt vielleicht hilfreich.

**Comment by silvabaum** [comment]
Habe dazu gerade Folgendes zur Umrechnung gefunden: 

![bildschirmfoto 2017-11-28 um 09 32 53](https://user-images.githubusercontent.com/33488569/33309675-2e318d54-d41f-11e7-8eb9-e996d1ed6001.png)

**Comment by jensschnitzler** [comment]
_notiz an mich selbst:_

```
.intro-quote p, .intro-nav *, .i-intro *, #nav>ul>li>a, .question-title * {
  …
  letter-spacing: -0.012;
}
```

**Comment by jensschnitzler** [comment]
**_bitte nach dem nächsten upload testen und ggf issue schließen_**
